###################################################################

# Created by write_sdc on Sat Feb  1 09:03:49 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -power mW -voltage V       \
-current mA
set_operating_conditions slow -library slow
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 1 [get_ports DONE]
set_ideal_network [get_ports CLK]
create_clock [get_ports CLK]  -period 6  -waveform {0 3}
set_clock_latency 0.5  [get_clocks CLK]
set_clock_uncertainty 0.1  [get_clocks CLK]
set_input_delay -clock CLK  1  [get_ports RST]
set_input_delay -clock CLK  1  [get_ports {V0[6]}]
set_input_delay -clock CLK  1  [get_ports {V0[5]}]
set_input_delay -clock CLK  1  [get_ports {V0[4]}]
set_input_delay -clock CLK  1  [get_ports {V0[3]}]
set_input_delay -clock CLK  1  [get_ports {V0[2]}]
set_input_delay -clock CLK  1  [get_ports {V0[1]}]
set_input_delay -clock CLK  1  [get_ports {V0[0]}]
set_input_delay -clock CLK  1  [get_ports {H0[6]}]
set_input_delay -clock CLK  1  [get_ports {H0[5]}]
set_input_delay -clock CLK  1  [get_ports {H0[4]}]
set_input_delay -clock CLK  1  [get_ports {H0[3]}]
set_input_delay -clock CLK  1  [get_ports {H0[2]}]
set_input_delay -clock CLK  1  [get_ports {H0[1]}]
set_input_delay -clock CLK  1  [get_ports {H0[0]}]
set_input_delay -clock CLK  1  [get_ports {SW[4]}]
set_input_delay -clock CLK  1  [get_ports {SW[3]}]
set_input_delay -clock CLK  1  [get_ports {SW[2]}]
set_input_delay -clock CLK  1  [get_ports {SW[1]}]
set_input_delay -clock CLK  1  [get_ports {SW[0]}]
set_input_delay -clock CLK  1  [get_ports {SH[4]}]
set_input_delay -clock CLK  1  [get_ports {SH[3]}]
set_input_delay -clock CLK  1  [get_ports {SH[2]}]
set_input_delay -clock CLK  1  [get_ports {SH[1]}]
set_input_delay -clock CLK  1  [get_ports {SH[0]}]
set_input_delay -clock CLK  1  [get_ports {TW[5]}]
set_input_delay -clock CLK  1  [get_ports {TW[4]}]
set_input_delay -clock CLK  1  [get_ports {TW[3]}]
set_input_delay -clock CLK  1  [get_ports {TW[2]}]
set_input_delay -clock CLK  1  [get_ports {TW[1]}]
set_input_delay -clock CLK  1  [get_ports {TW[0]}]
set_input_delay -clock CLK  1  [get_ports {TH[5]}]
set_input_delay -clock CLK  1  [get_ports {TH[4]}]
set_input_delay -clock CLK  1  [get_ports {TH[3]}]
set_input_delay -clock CLK  1  [get_ports {TH[2]}]
set_input_delay -clock CLK  1  [get_ports {TH[1]}]
set_input_delay -clock CLK  1  [get_ports {TH[0]}]
set_output_delay -clock CLK  1  [get_ports DONE]
set_drive 0.1  [get_ports CLK]
set_drive 0.1  [get_ports RST]
set_drive 0.1  [get_ports {V0[6]}]
set_drive 0.1  [get_ports {V0[5]}]
set_drive 0.1  [get_ports {V0[4]}]
set_drive 0.1  [get_ports {V0[3]}]
set_drive 0.1  [get_ports {V0[2]}]
set_drive 0.1  [get_ports {V0[1]}]
set_drive 0.1  [get_ports {V0[0]}]
set_drive 0.1  [get_ports {H0[6]}]
set_drive 0.1  [get_ports {H0[5]}]
set_drive 0.1  [get_ports {H0[4]}]
set_drive 0.1  [get_ports {H0[3]}]
set_drive 0.1  [get_ports {H0[2]}]
set_drive 0.1  [get_ports {H0[1]}]
set_drive 0.1  [get_ports {H0[0]}]
set_drive 0.1  [get_ports {SW[4]}]
set_drive 0.1  [get_ports {SW[3]}]
set_drive 0.1  [get_ports {SW[2]}]
set_drive 0.1  [get_ports {SW[1]}]
set_drive 0.1  [get_ports {SW[0]}]
set_drive 0.1  [get_ports {SH[4]}]
set_drive 0.1  [get_ports {SH[3]}]
set_drive 0.1  [get_ports {SH[2]}]
set_drive 0.1  [get_ports {SH[1]}]
set_drive 0.1  [get_ports {SH[0]}]
set_drive 0.1  [get_ports {TW[5]}]
set_drive 0.1  [get_ports {TW[4]}]
set_drive 0.1  [get_ports {TW[3]}]
set_drive 0.1  [get_ports {TW[2]}]
set_drive 0.1  [get_ports {TW[1]}]
set_drive 0.1  [get_ports {TW[0]}]
set_drive 0.1  [get_ports {TH[5]}]
set_drive 0.1  [get_ports {TH[4]}]
set_drive 0.1  [get_ports {TH[3]}]
set_drive 0.1  [get_ports {TH[2]}]
set_drive 0.1  [get_ports {TH[1]}]
set_drive 0.1  [get_ports {TH[0]}]
