###################################################################

# Created by write_sdc on Sun Jan 26 14:54:57 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max slow -max_library slow\
                         -min fast -min_library fast
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 0.1 [get_ports done]
set_load -pin_load 0.1 [get_ports sti_rd]
set_load -pin_load 0.1 [get_ports {sti_addr[9]}]
set_load -pin_load 0.1 [get_ports {sti_addr[8]}]
set_load -pin_load 0.1 [get_ports {sti_addr[7]}]
set_load -pin_load 0.1 [get_ports {sti_addr[6]}]
set_load -pin_load 0.1 [get_ports {sti_addr[5]}]
set_load -pin_load 0.1 [get_ports {sti_addr[4]}]
set_load -pin_load 0.1 [get_ports {sti_addr[3]}]
set_load -pin_load 0.1 [get_ports {sti_addr[2]}]
set_load -pin_load 0.1 [get_ports {sti_addr[1]}]
set_load -pin_load 0.1 [get_ports {sti_addr[0]}]
set_load -pin_load 0.1 [get_ports res_wr]
set_load -pin_load 0.1 [get_ports res_rd]
set_load -pin_load 0.1 [get_ports {res_addr[13]}]
set_load -pin_load 0.1 [get_ports {res_addr[12]}]
set_load -pin_load 0.1 [get_ports {res_addr[11]}]
set_load -pin_load 0.1 [get_ports {res_addr[10]}]
set_load -pin_load 0.1 [get_ports {res_addr[9]}]
set_load -pin_load 0.1 [get_ports {res_addr[8]}]
set_load -pin_load 0.1 [get_ports {res_addr[7]}]
set_load -pin_load 0.1 [get_ports {res_addr[6]}]
set_load -pin_load 0.1 [get_ports {res_addr[5]}]
set_load -pin_load 0.1 [get_ports {res_addr[4]}]
set_load -pin_load 0.1 [get_ports {res_addr[3]}]
set_load -pin_load 0.1 [get_ports {res_addr[2]}]
set_load -pin_load 0.1 [get_ports {res_addr[1]}]
set_load -pin_load 0.1 [get_ports {res_addr[0]}]
set_load -pin_load 0.1 [get_ports {res_do[7]}]
set_load -pin_load 0.1 [get_ports {res_do[6]}]
set_load -pin_load 0.1 [get_ports {res_do[5]}]
set_load -pin_load 0.1 [get_ports {res_do[4]}]
set_load -pin_load 0.1 [get_ports {res_do[3]}]
set_load -pin_load 0.1 [get_ports {res_do[2]}]
set_load -pin_load 0.1 [get_ports {res_do[1]}]
set_load -pin_load 0.1 [get_ports {res_do[0]}]
set_max_fanout 20 [get_ports clk]
set_max_fanout 20 [get_ports reset]
set_max_fanout 20 [get_ports {sti_di[15]}]
set_max_fanout 20 [get_ports {sti_di[14]}]
set_max_fanout 20 [get_ports {sti_di[13]}]
set_max_fanout 20 [get_ports {sti_di[12]}]
set_max_fanout 20 [get_ports {sti_di[11]}]
set_max_fanout 20 [get_ports {sti_di[10]}]
set_max_fanout 20 [get_ports {sti_di[9]}]
set_max_fanout 20 [get_ports {sti_di[8]}]
set_max_fanout 20 [get_ports {sti_di[7]}]
set_max_fanout 20 [get_ports {sti_di[6]}]
set_max_fanout 20 [get_ports {sti_di[5]}]
set_max_fanout 20 [get_ports {sti_di[4]}]
set_max_fanout 20 [get_ports {sti_di[3]}]
set_max_fanout 20 [get_ports {sti_di[2]}]
set_max_fanout 20 [get_ports {sti_di[1]}]
set_max_fanout 20 [get_ports {sti_di[0]}]
set_max_fanout 20 [get_ports {res_di[7]}]
set_max_fanout 20 [get_ports {res_di[6]}]
set_max_fanout 20 [get_ports {res_di[5]}]
set_max_fanout 20 [get_ports {res_di[4]}]
set_max_fanout 20 [get_ports {res_di[3]}]
set_max_fanout 20 [get_ports {res_di[2]}]
set_max_fanout 20 [get_ports {res_di[1]}]
set_max_fanout 20 [get_ports {res_di[0]}]
create_clock [get_ports clk]  -period 3.5  -waveform {0 1.75}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty 0.1  [get_clocks clk]
set_input_delay -clock clk  1.75  [get_ports reset]
set_input_delay -clock clk  1.75  [get_ports {sti_di[15]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[14]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[13]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[12]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[11]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[10]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[9]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[8]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[7]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[6]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[5]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[4]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[3]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[2]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[1]}]
set_input_delay -clock clk  1.75  [get_ports {sti_di[0]}]
set_input_delay -clock clk  1.75  [get_ports {res_di[7]}]
set_input_delay -clock clk  1.75  [get_ports {res_di[6]}]
set_input_delay -clock clk  1.75  [get_ports {res_di[5]}]
set_input_delay -clock clk  1.75  [get_ports {res_di[4]}]
set_input_delay -clock clk  1.75  [get_ports {res_di[3]}]
set_input_delay -clock clk  1.75  [get_ports {res_di[2]}]
set_input_delay -clock clk  1.75  [get_ports {res_di[1]}]
set_input_delay -clock clk  1.75  [get_ports {res_di[0]}]
set_output_delay -clock clk  0.5  [get_ports done]
set_output_delay -clock clk  0.5  [get_ports sti_rd]
set_output_delay -clock clk  0.5  [get_ports {sti_addr[9]}]
set_output_delay -clock clk  0.5  [get_ports {sti_addr[8]}]
set_output_delay -clock clk  0.5  [get_ports {sti_addr[7]}]
set_output_delay -clock clk  0.5  [get_ports {sti_addr[6]}]
set_output_delay -clock clk  0.5  [get_ports {sti_addr[5]}]
set_output_delay -clock clk  0.5  [get_ports {sti_addr[4]}]
set_output_delay -clock clk  0.5  [get_ports {sti_addr[3]}]
set_output_delay -clock clk  0.5  [get_ports {sti_addr[2]}]
set_output_delay -clock clk  0.5  [get_ports {sti_addr[1]}]
set_output_delay -clock clk  0.5  [get_ports {sti_addr[0]}]
set_output_delay -clock clk  0.5  [get_ports res_wr]
set_output_delay -clock clk  0.5  [get_ports res_rd]
set_output_delay -clock clk  0.5  [get_ports {res_addr[13]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[12]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[11]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[10]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[9]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[8]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[7]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[6]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[5]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[4]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[3]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[2]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[1]}]
set_output_delay -clock clk  0.5  [get_ports {res_addr[0]}]
set_output_delay -clock clk  0.5  [get_ports {res_do[7]}]
set_output_delay -clock clk  0.5  [get_ports {res_do[6]}]
set_output_delay -clock clk  0.5  [get_ports {res_do[5]}]
set_output_delay -clock clk  0.5  [get_ports {res_do[4]}]
set_output_delay -clock clk  0.5  [get_ports {res_do[3]}]
set_output_delay -clock clk  0.5  [get_ports {res_do[2]}]
set_output_delay -clock clk  0.5  [get_ports {res_do[1]}]
set_output_delay -clock clk  0.5  [get_ports {res_do[0]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports reset]
set_drive 1  [get_ports {sti_di[15]}]
set_drive 1  [get_ports {sti_di[14]}]
set_drive 1  [get_ports {sti_di[13]}]
set_drive 1  [get_ports {sti_di[12]}]
set_drive 1  [get_ports {sti_di[11]}]
set_drive 1  [get_ports {sti_di[10]}]
set_drive 1  [get_ports {sti_di[9]}]
set_drive 1  [get_ports {sti_di[8]}]
set_drive 1  [get_ports {sti_di[7]}]
set_drive 1  [get_ports {sti_di[6]}]
set_drive 1  [get_ports {sti_di[5]}]
set_drive 1  [get_ports {sti_di[4]}]
set_drive 1  [get_ports {sti_di[3]}]
set_drive 1  [get_ports {sti_di[2]}]
set_drive 1  [get_ports {sti_di[1]}]
set_drive 1  [get_ports {sti_di[0]}]
set_drive 1  [get_ports {res_di[7]}]
set_drive 1  [get_ports {res_di[6]}]
set_drive 1  [get_ports {res_di[5]}]
set_drive 1  [get_ports {res_di[4]}]
set_drive 1  [get_ports {res_di[3]}]
set_drive 1  [get_ports {res_di[2]}]
set_drive 1  [get_ports {res_di[1]}]
set_drive 1  [get_ports {res_di[0]}]
