 
****************************************
Report : resources
Design : LASER
Version: U-2022.12
Date   : Fri Jan 31 07:41:29 2025
****************************************


Resource Report for this hierarchy in file ./LASER.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_5        | DW_cmp         | width=4    | gte_68 (LASER.v:68)        |
| gte_x_6        | DW_cmp         | width=4    | gte_69 (LASER.v:69)        |
| sub_x_13       | DW01_dec       | width=3    | sub_133 (LASER.v:133)      |
| add_x_15       | DW01_add       | width=4    | add_148 (LASER.v:148)      |
| add_x_17       | DW01_add       | width=4    | add_163 (LASER.v:163)      |
| add_x_27       | DW01_inc       | width=2    | add_275 (LASER.v:275)      |
| sub_x_35       | DW01_sub       | width=5    | genblk1[0].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_36       | DW01_sub       | width=5    | genblk1[0].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_37       | DW01_inc       | width=4    | genblk1[0].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_39       | DW01_inc       | width=4    | genblk1[0].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_41       | DW_cmp         | width=4    | genblk1[0].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_42       | DW_cmp         | width=4    | genblk1[0].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_43       | DW_cmp         | width=4    | genblk1[0].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_44       | DW01_sub       | width=5    | genblk1[19].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_45       | DW01_sub       | width=5    | genblk1[19].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_46       | DW01_inc       | width=4    | genblk1[19].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_48       | DW01_inc       | width=4    | genblk1[19].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_50       | DW_cmp         | width=4    | genblk1[19].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_51       | DW_cmp         | width=4    | genblk1[19].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_52       | DW_cmp         | width=4    | genblk1[19].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_53       | DW01_sub       | width=5    | genblk1[19].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_54       | DW01_sub       | width=5    | genblk1[19].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_55       | DW01_inc       | width=4    | genblk1[19].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_57       | DW01_inc       | width=4    | genblk1[19].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_59       | DW_cmp         | width=4    | genblk1[19].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_60       | DW_cmp         | width=4    | genblk1[19].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_61       | DW_cmp         | width=4    | genblk1[19].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_62       | DW01_sub       | width=5    | genblk1[18].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_63       | DW01_sub       | width=5    | genblk1[18].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_64       | DW01_inc       | width=4    | genblk1[18].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_66       | DW01_inc       | width=4    | genblk1[18].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_68       | DW_cmp         | width=4    | genblk1[18].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_69       | DW_cmp         | width=4    | genblk1[18].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_70       | DW_cmp         | width=4    | genblk1[18].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_71       | DW01_sub       | width=5    | genblk1[18].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_72       | DW01_sub       | width=5    | genblk1[18].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_73       | DW01_inc       | width=4    | genblk1[18].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_75       | DW01_inc       | width=4    | genblk1[18].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_77       | DW_cmp         | width=4    | genblk1[18].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_78       | DW_cmp         | width=4    | genblk1[18].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_79       | DW_cmp         | width=4    | genblk1[18].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_80       | DW01_sub       | width=5    | genblk1[17].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_81       | DW01_sub       | width=5    | genblk1[17].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_82       | DW01_inc       | width=4    | genblk1[17].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_84       | DW01_inc       | width=4    | genblk1[17].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_86       | DW_cmp         | width=4    | genblk1[17].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_87       | DW_cmp         | width=4    | genblk1[17].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_88       | DW_cmp         | width=4    | genblk1[17].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_89       | DW01_sub       | width=5    | genblk1[17].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_90       | DW01_sub       | width=5    | genblk1[17].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_91       | DW01_inc       | width=4    | genblk1[17].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_93       | DW01_inc       | width=4    | genblk1[17].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_95       | DW_cmp         | width=4    | genblk1[17].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_96       | DW_cmp         | width=4    | genblk1[17].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_97       | DW_cmp         | width=4    | genblk1[17].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_98       | DW01_sub       | width=5    | genblk1[16].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_99       | DW01_sub       | width=5    | genblk1[16].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_100      | DW01_inc       | width=4    | genblk1[16].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_102      | DW01_inc       | width=4    | genblk1[16].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_104      | DW_cmp         | width=4    | genblk1[16].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_105      | DW_cmp         | width=4    | genblk1[16].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_106      | DW_cmp         | width=4    | genblk1[16].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_107      | DW01_sub       | width=5    | genblk1[16].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_108      | DW01_sub       | width=5    | genblk1[16].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_109      | DW01_inc       | width=4    | genblk1[16].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_111      | DW01_inc       | width=4    | genblk1[16].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_113      | DW_cmp         | width=4    | genblk1[16].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_114      | DW_cmp         | width=4    | genblk1[16].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_115      | DW_cmp         | width=4    | genblk1[16].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_116      | DW01_sub       | width=5    | genblk1[15].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_117      | DW01_sub       | width=5    | genblk1[15].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_118      | DW01_inc       | width=4    | genblk1[15].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_120      | DW01_inc       | width=4    | genblk1[15].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_122      | DW_cmp         | width=4    | genblk1[15].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_123      | DW_cmp         | width=4    | genblk1[15].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_124      | DW_cmp         | width=4    | genblk1[15].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_125      | DW01_sub       | width=5    | genblk1[15].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_126      | DW01_sub       | width=5    | genblk1[15].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_127      | DW01_inc       | width=4    | genblk1[15].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_129      | DW01_inc       | width=4    | genblk1[15].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_131      | DW_cmp         | width=4    | genblk1[15].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_132      | DW_cmp         | width=4    | genblk1[15].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_133      | DW_cmp         | width=4    | genblk1[15].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_134      | DW01_sub       | width=5    | genblk1[14].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_135      | DW01_sub       | width=5    | genblk1[14].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_136      | DW01_inc       | width=4    | genblk1[14].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_138      | DW01_inc       | width=4    | genblk1[14].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_140      | DW_cmp         | width=4    | genblk1[14].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_141      | DW_cmp         | width=4    | genblk1[14].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_142      | DW_cmp         | width=4    | genblk1[14].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_143      | DW01_sub       | width=5    | genblk1[14].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_144      | DW01_sub       | width=5    | genblk1[14].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_145      | DW01_inc       | width=4    | genblk1[14].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_147      | DW01_inc       | width=4    | genblk1[14].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_149      | DW_cmp         | width=4    | genblk1[14].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_150      | DW_cmp         | width=4    | genblk1[14].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_151      | DW_cmp         | width=4    | genblk1[14].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_152      | DW01_sub       | width=5    | genblk1[13].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_153      | DW01_sub       | width=5    | genblk1[13].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_154      | DW01_inc       | width=4    | genblk1[13].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_156      | DW01_inc       | width=4    | genblk1[13].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_158      | DW_cmp         | width=4    | genblk1[13].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_159      | DW_cmp         | width=4    | genblk1[13].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_160      | DW_cmp         | width=4    | genblk1[13].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_161      | DW01_sub       | width=5    | genblk1[13].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_162      | DW01_sub       | width=5    | genblk1[13].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_163      | DW01_inc       | width=4    | genblk1[13].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_165      | DW01_inc       | width=4    | genblk1[13].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_167      | DW_cmp         | width=4    | genblk1[13].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_168      | DW_cmp         | width=4    | genblk1[13].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_169      | DW_cmp         | width=4    | genblk1[13].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_170      | DW01_sub       | width=5    | genblk1[12].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_171      | DW01_sub       | width=5    | genblk1[12].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_172      | DW01_inc       | width=4    | genblk1[12].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_174      | DW01_inc       | width=4    | genblk1[12].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_176      | DW_cmp         | width=4    | genblk1[12].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_177      | DW_cmp         | width=4    | genblk1[12].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_178      | DW_cmp         | width=4    | genblk1[12].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_179      | DW01_sub       | width=5    | genblk1[12].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_180      | DW01_sub       | width=5    | genblk1[12].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_181      | DW01_inc       | width=4    | genblk1[12].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_183      | DW01_inc       | width=4    | genblk1[12].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_185      | DW_cmp         | width=4    | genblk1[12].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_186      | DW_cmp         | width=4    | genblk1[12].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_187      | DW_cmp         | width=4    | genblk1[12].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_188      | DW01_sub       | width=5    | genblk1[11].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_189      | DW01_sub       | width=5    | genblk1[11].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_190      | DW01_inc       | width=4    | genblk1[11].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_192      | DW01_inc       | width=4    | genblk1[11].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_194      | DW_cmp         | width=4    | genblk1[11].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_195      | DW_cmp         | width=4    | genblk1[11].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_196      | DW_cmp         | width=4    | genblk1[11].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_197      | DW01_sub       | width=5    | genblk1[11].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_198      | DW01_sub       | width=5    | genblk1[11].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_199      | DW01_inc       | width=4    | genblk1[11].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_201      | DW01_inc       | width=4    | genblk1[11].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_203      | DW_cmp         | width=4    | genblk1[11].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_204      | DW_cmp         | width=4    | genblk1[11].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_205      | DW_cmp         | width=4    | genblk1[11].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_206      | DW01_sub       | width=5    | genblk1[10].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_207      | DW01_sub       | width=5    | genblk1[10].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_208      | DW01_inc       | width=4    | genblk1[10].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_210      | DW01_inc       | width=4    | genblk1[10].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_212      | DW_cmp         | width=4    | genblk1[10].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_213      | DW_cmp         | width=4    | genblk1[10].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_214      | DW_cmp         | width=4    | genblk1[10].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_215      | DW01_sub       | width=5    | genblk1[10].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_216      | DW01_sub       | width=5    | genblk1[10].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_217      | DW01_inc       | width=4    | genblk1[10].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_219      | DW01_inc       | width=4    | genblk1[10].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_221      | DW_cmp         | width=4    | genblk1[10].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_222      | DW_cmp         | width=4    | genblk1[10].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_223      | DW_cmp         | width=4    | genblk1[10].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_224      | DW01_sub       | width=5    | genblk1[9].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_225      | DW01_sub       | width=5    | genblk1[9].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_226      | DW01_inc       | width=4    | genblk1[9].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_228      | DW01_inc       | width=4    | genblk1[9].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_230      | DW_cmp         | width=4    | genblk1[9].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_231      | DW_cmp         | width=4    | genblk1[9].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_232      | DW_cmp         | width=4    | genblk1[9].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_233      | DW01_sub       | width=5    | genblk1[9].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_234      | DW01_sub       | width=5    | genblk1[9].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_235      | DW01_inc       | width=4    | genblk1[9].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_237      | DW01_inc       | width=4    | genblk1[9].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_239      | DW_cmp         | width=4    | genblk1[9].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_240      | DW_cmp         | width=4    | genblk1[9].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_241      | DW_cmp         | width=4    | genblk1[9].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_242      | DW01_sub       | width=5    | genblk1[8].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_243      | DW01_sub       | width=5    | genblk1[8].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_244      | DW01_inc       | width=4    | genblk1[8].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_246      | DW01_inc       | width=4    | genblk1[8].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_248      | DW_cmp         | width=4    | genblk1[8].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_249      | DW_cmp         | width=4    | genblk1[8].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_250      | DW_cmp         | width=4    | genblk1[8].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_251      | DW01_sub       | width=5    | genblk1[8].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_252      | DW01_sub       | width=5    | genblk1[8].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_253      | DW01_inc       | width=4    | genblk1[8].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_255      | DW01_inc       | width=4    | genblk1[8].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_257      | DW_cmp         | width=4    | genblk1[8].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_258      | DW_cmp         | width=4    | genblk1[8].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_259      | DW_cmp         | width=4    | genblk1[8].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_260      | DW01_sub       | width=5    | genblk1[7].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_261      | DW01_sub       | width=5    | genblk1[7].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_262      | DW01_inc       | width=4    | genblk1[7].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_264      | DW01_inc       | width=4    | genblk1[7].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_266      | DW_cmp         | width=4    | genblk1[7].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_267      | DW_cmp         | width=4    | genblk1[7].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_268      | DW_cmp         | width=4    | genblk1[7].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_269      | DW01_sub       | width=5    | genblk1[7].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_270      | DW01_sub       | width=5    | genblk1[7].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_271      | DW01_inc       | width=4    | genblk1[7].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_273      | DW01_inc       | width=4    | genblk1[7].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_275      | DW_cmp         | width=4    | genblk1[7].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_276      | DW_cmp         | width=4    | genblk1[7].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_277      | DW_cmp         | width=4    | genblk1[7].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_278      | DW01_sub       | width=5    | genblk1[6].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_279      | DW01_sub       | width=5    | genblk1[6].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_280      | DW01_inc       | width=4    | genblk1[6].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_282      | DW01_inc       | width=4    | genblk1[6].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_284      | DW_cmp         | width=4    | genblk1[6].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_285      | DW_cmp         | width=4    | genblk1[6].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_286      | DW_cmp         | width=4    | genblk1[6].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_287      | DW01_sub       | width=5    | genblk1[6].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_288      | DW01_sub       | width=5    | genblk1[6].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_289      | DW01_inc       | width=4    | genblk1[6].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_291      | DW01_inc       | width=4    | genblk1[6].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_293      | DW_cmp         | width=4    | genblk1[6].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_294      | DW_cmp         | width=4    | genblk1[6].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_295      | DW_cmp         | width=4    | genblk1[6].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_296      | DW01_sub       | width=5    | genblk1[5].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_297      | DW01_sub       | width=5    | genblk1[5].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_298      | DW01_inc       | width=4    | genblk1[5].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_300      | DW01_inc       | width=4    | genblk1[5].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_302      | DW_cmp         | width=4    | genblk1[5].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_303      | DW_cmp         | width=4    | genblk1[5].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_304      | DW_cmp         | width=4    | genblk1[5].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_305      | DW01_sub       | width=5    | genblk1[5].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_306      | DW01_sub       | width=5    | genblk1[5].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_307      | DW01_inc       | width=4    | genblk1[5].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_309      | DW01_inc       | width=4    | genblk1[5].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_311      | DW_cmp         | width=4    | genblk1[5].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_312      | DW_cmp         | width=4    | genblk1[5].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_313      | DW_cmp         | width=4    | genblk1[5].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_314      | DW01_sub       | width=5    | genblk1[4].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_315      | DW01_sub       | width=5    | genblk1[4].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_316      | DW01_inc       | width=4    | genblk1[4].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_318      | DW01_inc       | width=4    | genblk1[4].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_320      | DW_cmp         | width=4    | genblk1[4].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_321      | DW_cmp         | width=4    | genblk1[4].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_322      | DW_cmp         | width=4    | genblk1[4].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_323      | DW01_sub       | width=5    | genblk1[4].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_324      | DW01_sub       | width=5    | genblk1[4].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_325      | DW01_inc       | width=4    | genblk1[4].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_327      | DW01_inc       | width=4    | genblk1[4].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_329      | DW_cmp         | width=4    | genblk1[4].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_330      | DW_cmp         | width=4    | genblk1[4].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_331      | DW_cmp         | width=4    | genblk1[4].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_332      | DW01_sub       | width=5    | genblk1[3].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_333      | DW01_sub       | width=5    | genblk1[3].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_334      | DW01_inc       | width=4    | genblk1[3].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_336      | DW01_inc       | width=4    | genblk1[3].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_338      | DW_cmp         | width=4    | genblk1[3].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_339      | DW_cmp         | width=4    | genblk1[3].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_340      | DW_cmp         | width=4    | genblk1[3].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_341      | DW01_sub       | width=5    | genblk1[3].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_342      | DW01_sub       | width=5    | genblk1[3].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_343      | DW01_inc       | width=4    | genblk1[3].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_345      | DW01_inc       | width=4    | genblk1[3].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_347      | DW_cmp         | width=4    | genblk1[3].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_348      | DW_cmp         | width=4    | genblk1[3].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_349      | DW_cmp         | width=4    | genblk1[3].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_350      | DW01_sub       | width=5    | genblk1[2].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_351      | DW01_sub       | width=5    | genblk1[2].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_352      | DW01_inc       | width=4    | genblk1[2].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_354      | DW01_inc       | width=4    | genblk1[2].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_356      | DW_cmp         | width=4    | genblk1[2].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_357      | DW_cmp         | width=4    | genblk1[2].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_358      | DW_cmp         | width=4    | genblk1[2].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_359      | DW01_sub       | width=5    | genblk1[2].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_360      | DW01_sub       | width=5    | genblk1[2].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_361      | DW01_inc       | width=4    | genblk1[2].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_363      | DW01_inc       | width=4    | genblk1[2].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_365      | DW_cmp         | width=4    | genblk1[2].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_366      | DW_cmp         | width=4    | genblk1[2].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_367      | DW_cmp         | width=4    | genblk1[2].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_368      | DW01_sub       | width=5    | genblk1[1].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_369      | DW01_sub       | width=5    | genblk1[1].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_370      | DW01_inc       | width=4    | genblk1[1].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_372      | DW01_inc       | width=4    | genblk1[1].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_374      | DW_cmp         | width=4    | genblk1[1].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_375      | DW_cmp         | width=4    | genblk1[1].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_376      | DW_cmp         | width=4    | genblk1[1].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| sub_x_377      | DW01_sub       | width=5    | genblk1[1].det_inside_inst/det_inside_1/sub_319 (LASER.v:319) |
| sub_x_378      | DW01_sub       | width=5    | genblk1[1].det_inside_inst/det_inside_1/sub_320 (LASER.v:320) |
| add_x_379      | DW01_inc       | width=4    | genblk1[1].det_inside_inst/det_inside_1/add_322 (LASER.v:322) |
| add_x_381      | DW01_inc       | width=4    | genblk1[1].det_inside_inst/det_inside_1/add_323 (LASER.v:323) |
| lte_x_383      | DW_cmp         | width=4    | genblk1[1].det_inside_inst/det_inside_1/lte_325 (LASER.v:325) |
| lte_x_384      | DW_cmp         | width=4    | genblk1[1].det_inside_inst/det_inside_1/lte_325_2 (LASER.v:325) |
| lte_x_385      | DW_cmp         | width=4    | genblk1[1].det_inside_inst/det_inside_1/lte_325_5 (LASER.v:325) |
| sub_x_386      | DW01_sub       | width=5    | genblk1[0].det_inside_inst/det_inside_2/sub_319 (LASER.v:319) |
| sub_x_387      | DW01_sub       | width=5    | genblk1[0].det_inside_inst/det_inside_2/sub_320 (LASER.v:320) |
| add_x_388      | DW01_inc       | width=4    | genblk1[0].det_inside_inst/det_inside_2/add_322 (LASER.v:322) |
| add_x_390      | DW01_inc       | width=4    | genblk1[0].det_inside_inst/det_inside_2/add_323 (LASER.v:323) |
| lte_x_392      | DW_cmp         | width=4    | genblk1[0].det_inside_inst/det_inside_2/lte_325 (LASER.v:325) |
| lte_x_393      | DW_cmp         | width=4    | genblk1[0].det_inside_inst/det_inside_2/lte_325_2 (LASER.v:325) |
| lte_x_394      | DW_cmp         | width=4    | genblk1[0].det_inside_inst/det_inside_2/lte_325_5 (LASER.v:325) |
| lte_x_395      | DW_cmp         | width=4    | genblk1[0].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|         | genblk1[0].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_396      | DW_cmp         | width=4    | genblk1[19].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|        | genblk1[19].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_397      | DW_cmp         | width=4    | genblk1[19].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|        | genblk1[19].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_398      | DW_cmp         | width=4    | genblk1[18].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|        | genblk1[18].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_399      | DW_cmp         | width=4    | genblk1[18].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|        | genblk1[18].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_400      | DW_cmp         | width=4    | genblk1[17].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|        | genblk1[17].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_401      | DW_cmp         | width=4    | genblk1[17].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|        | genblk1[17].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_402      | DW_cmp         | width=4    | genblk1[16].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|        | genblk1[16].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_403      | DW_cmp         | width=4    | genblk1[16].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|        | genblk1[16].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_404      | DW_cmp         | width=4    | genblk1[15].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|        | genblk1[15].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_405      | DW_cmp         | width=4    | genblk1[15].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|        | genblk1[15].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_406      | DW_cmp         | width=4    | genblk1[14].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|        | genblk1[14].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_407      | DW_cmp         | width=4    | genblk1[14].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|        | genblk1[14].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_408      | DW_cmp         | width=4    | genblk1[13].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|        | genblk1[13].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_409      | DW_cmp         | width=4    | genblk1[13].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|        | genblk1[13].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_410      | DW_cmp         | width=4    | genblk1[12].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|        | genblk1[12].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_411      | DW_cmp         | width=4    | genblk1[12].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|        | genblk1[12].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_412      | DW_cmp         | width=4    | genblk1[11].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|        | genblk1[11].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_413      | DW_cmp         | width=4    | genblk1[11].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|        | genblk1[11].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_414      | DW_cmp         | width=4    | genblk1[10].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|        | genblk1[10].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_415      | DW_cmp         | width=4    | genblk1[10].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|        | genblk1[10].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_416      | DW_cmp         | width=4    | genblk1[9].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|         | genblk1[9].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_417      | DW_cmp         | width=4    | genblk1[9].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|         | genblk1[9].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_418      | DW_cmp         | width=4    | genblk1[8].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|         | genblk1[8].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_419      | DW_cmp         | width=4    | genblk1[8].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|         | genblk1[8].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_420      | DW_cmp         | width=4    | genblk1[7].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|         | genblk1[7].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_421      | DW_cmp         | width=4    | genblk1[7].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|         | genblk1[7].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_422      | DW_cmp         | width=4    | genblk1[6].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|         | genblk1[6].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_423      | DW_cmp         | width=4    | genblk1[6].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|         | genblk1[6].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_424      | DW_cmp         | width=4    | genblk1[5].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|         | genblk1[5].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_425      | DW_cmp         | width=4    | genblk1[5].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|         | genblk1[5].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_426      | DW_cmp         | width=4    | genblk1[4].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|         | genblk1[4].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_427      | DW_cmp         | width=4    | genblk1[4].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|         | genblk1[4].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_428      | DW_cmp         | width=4    | genblk1[3].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|         | genblk1[3].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_429      | DW_cmp         | width=4    | genblk1[3].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|         | genblk1[3].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_430      | DW_cmp         | width=4    | genblk1[2].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|         | genblk1[2].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_431      | DW_cmp         | width=4    | genblk1[2].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|         | genblk1[2].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_432      | DW_cmp         | width=4    | genblk1[1].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|         | genblk1[1].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| lte_x_433      | DW_cmp         | width=4    | genblk1[1].det_inside_inst/det_inside_1/lte_325_3 (LASER.v:325) |
|         | genblk1[1].det_inside_inst/det_inside_1/lte_325_4 (LASER.v:325) |
| lte_x_434      | DW_cmp         | width=4    | genblk1[0].det_inside_inst/det_inside_2/lte_325_3 (LASER.v:325) |
|         | genblk1[0].det_inside_inst/det_inside_2/lte_325_4 (LASER.v:325) |
| DP_OP_839J1_122_8998            |            |                            |
|                | DP_OP_839J1_122_8998 |      |                            |
| DP_OP_843J1_123_5647            |            |                            |
|                | DP_OP_843J1_123_5647 |      |                            |
=============================================================================

Datapath Report for DP_OP_839J1_122_8998
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_839J1_122_8998 | add_61 (LASER.v:61) add_61_2 (LASER.v:61)           |
|                      | add_61_3 (LASER.v:61) add_61_4 (LASER.v:61)         |
|                      | add_61_5 (LASER.v:61) add_61_6 (LASER.v:61)         |
|                      | add_61_7 (LASER.v:61) add_61_8 (LASER.v:61)         |
|                      | add_61_9 (LASER.v:61) add_61_10 (LASER.v:61)        |
|                      | add_61_11 (LASER.v:61) add_61_12 (LASER.v:61)       |
|                      | add_61_13 (LASER.v:61) add_61_14 (LASER.v:61)       |
|                      | add_61_15 (LASER.v:61) add_61_16 (LASER.v:61)       |
|                      | add_61_17 (LASER.v:61) add_61_18 (LASER.v:61)       |
|                      | add_61_19 (LASER.v:61) add_61_20 (LASER.v:61)       |
|                      | gte_66 (LASER.v:66) gt_262 (LASER.v:262)            |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 5     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| I3    | PI   | Unsigned | 1     |                                          |
| I4    | PI   | Unsigned | 1     |                                          |
| I5    | PI   | Unsigned | 1     |                                          |
| I6    | PI   | Unsigned | 1     |                                          |
| I7    | PI   | Unsigned | 1     |                                          |
| I8    | PI   | Unsigned | 1     |                                          |
| I9    | PI   | Unsigned | 1     |                                          |
| I10   | PI   | Unsigned | 1     |                                          |
| I11   | PI   | Unsigned | 1     |                                          |
| I12   | PI   | Unsigned | 1     |                                          |
| I13   | PI   | Unsigned | 1     |                                          |
| I14   | PI   | Unsigned | 1     |                                          |
| I15   | PI   | Unsigned | 1     |                                          |
| I16   | PI   | Unsigned | 1     |                                          |
| I17   | PI   | Unsigned | 1     |                                          |
| I18   | PI   | Unsigned | 1     |                                          |
| I19   | PI   | Unsigned | 1     |                                          |
| I20   | PI   | Unsigned | 1     |                                          |
| I21   | PI   | Unsigned | 1     |                                          |
| I22   | PI   | Unsigned | 5     |                                          |
| O1    | PO   | Unsigned | 6     | I1 + I2 + I3 + I4 + I5 + I6 + I7 + I8 + I9 + I10 + I11 + I12 + I13 + I14 + I15 + I16 + I17 + I18 + I19 + I20 + I21 (LASER.v:61) |
| O2    | PO   | Unsigned | 1     | O1 >= I22 (LASER.v:66)                   |
| O3    | PO   | Unsigned | 1     | O1 > I22 (LASER.v:262)                   |
==============================================================================

Datapath Report for DP_OP_843J1_123_5647
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_843J1_123_5647 | add_183 (LASER.v:183) add_180 (LASER.v:180)         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 6     |                                          |
| I2    | PI   | Unsigned | 5     |                                          |
| O1    | PO   | Unsigned | 6     | I1 + I2 ( LASER.v:180 LASER.v:183 )      |
==============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'genblk1[0].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[0].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[19].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[19].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[19].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[19].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[18].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[18].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[18].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[18].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[17].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[17].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[17].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[17].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[16].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[16].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[16].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[16].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[15].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[15].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[15].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[15].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[14].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[14].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[14].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[14].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[13].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[13].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[13].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[13].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[12].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[12].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[12].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[12].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[11].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[11].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[11].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[11].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[10].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[10].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[10].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[10].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[9].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[9].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[9].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[9].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[8].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[8].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[8].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[8].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[7].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[7].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[7].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[7].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[6].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[6].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[6].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[6].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[5].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[5].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[5].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[5].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[4].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[4].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[4].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[4].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[3].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[3].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[3].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[3].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[2].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[2].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[2].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[2].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[1].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[1].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[1].det_inside_inst/det_inside_1/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[1].det_inside_inst/det_inside_1/C60 (LASER.v:323)'.  (HDL-120)

Information: Operator associated with resources 'genblk1[0].det_inside_inst/det_inside_2/add_323 (LASER.v:323)' in design 'LASER' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'genblk1[0].det_inside_inst/det_inside_2/C60 (LASER.v:323)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| gte_x_5            | DW_cmp           | apparch (area)     |                |
| gte_x_6            | DW_cmp           | apparch (area)     |                |
| sub_x_13           | DW01_dec         | apparch (area)     |                |
| add_x_15           | DW01_add         | apparch (area)     |                |
| add_x_17           | DW01_add         | apparch (area)     |                |
| add_x_27           | DW01_inc         | apparch (area)     |                |
| sub_x_35           | DW01_sub         | apparch (area)     |                |
| sub_x_36           | DW01_sub         | apparch (area)     |                |
| add_x_37           | DW01_inc         | apparch (area)     |                |
| add_x_39           | DW01_inc         | apparch (area)     |                |
| lte_x_41           | DW_cmp           | apparch (area)     |                |
| lte_x_42           | DW_cmp           | apparch (area)     |                |
| lte_x_43           | DW_cmp           | apparch (area)     |                |
| sub_x_44           | DW01_sub         | apparch (area)     |                |
| sub_x_45           | DW01_sub         | apparch (area)     |                |
| add_x_46           | DW01_inc         | apparch (area)     |                |
| add_x_48           | DW01_inc         | apparch (area)     |                |
| lte_x_50           | DW_cmp           | apparch (area)     |                |
| lte_x_51           | DW_cmp           | apparch (area)     |                |
| lte_x_52           | DW_cmp           | apparch (area)     |                |
| sub_x_53           | DW01_sub         | apparch (area)     |                |
| sub_x_54           | DW01_sub         | apparch (area)     |                |
| add_x_55           | DW01_inc         | apparch (area)     |                |
| add_x_57           | DW01_inc         | apparch (area)     |                |
| lte_x_59           | DW_cmp           | apparch (area)     |                |
| lte_x_60           | DW_cmp           | apparch (area)     |                |
| lte_x_61           | DW_cmp           | apparch (area)     |                |
| sub_x_62           | DW01_sub         | apparch (area)     |                |
| sub_x_63           | DW01_sub         | apparch (area)     |                |
| add_x_64           | DW01_inc         | apparch (area)     |                |
| add_x_66           | DW01_inc         | apparch (area)     |                |
| lte_x_68           | DW_cmp           | apparch (area)     |                |
| lte_x_69           | DW_cmp           | apparch (area)     |                |
| lte_x_70           | DW_cmp           | apparch (area)     |                |
| sub_x_71           | DW01_sub         | apparch (area)     |                |
| sub_x_72           | DW01_sub         | apparch (area)     |                |
| add_x_73           | DW01_inc         | apparch (area)     |                |
| add_x_75           | DW01_inc         | apparch (area)     |                |
| lte_x_77           | DW_cmp           | apparch (area)     |                |
| lte_x_78           | DW_cmp           | apparch (area)     |                |
| lte_x_79           | DW_cmp           | apparch (area)     |                |
| sub_x_80           | DW01_sub         | apparch (area)     |                |
| sub_x_81           | DW01_sub         | apparch (area)     |                |
| add_x_82           | DW01_inc         | apparch (area)     |                |
| add_x_84           | DW01_inc         | apparch (area)     |                |
| lte_x_86           | DW_cmp           | apparch (area)     |                |
| lte_x_87           | DW_cmp           | apparch (area)     |                |
| lte_x_88           | DW_cmp           | apparch (area)     |                |
| sub_x_89           | DW01_sub         | apparch (area)     |                |
| sub_x_90           | DW01_sub         | apparch (area)     |                |
| add_x_91           | DW01_inc         | apparch (area)     |                |
| add_x_93           | DW01_inc         | apparch (area)     |                |
| lte_x_95           | DW_cmp           | apparch (area)     |                |
| lte_x_96           | DW_cmp           | apparch (area)     |                |
| lte_x_97           | DW_cmp           | apparch (area)     |                |
| sub_x_98           | DW01_sub         | apparch (area)     |                |
| sub_x_99           | DW01_sub         | apparch (area)     |                |
| add_x_100          | DW01_inc         | apparch (area)     |                |
| add_x_102          | DW01_inc         | apparch (area)     |                |
| lte_x_104          | DW_cmp           | apparch (area)     |                |
| lte_x_105          | DW_cmp           | apparch (area)     |                |
| lte_x_106          | DW_cmp           | apparch (area)     |                |
| sub_x_107          | DW01_sub         | apparch (area)     |                |
| sub_x_108          | DW01_sub         | apparch (area)     |                |
| add_x_109          | DW01_inc         | apparch (area)     |                |
| add_x_111          | DW01_inc         | apparch (area)     |                |
| lte_x_113          | DW_cmp           | apparch (area)     |                |
| lte_x_114          | DW_cmp           | apparch (area)     |                |
| lte_x_115          | DW_cmp           | apparch (area)     |                |
| sub_x_116          | DW01_sub         | apparch (area)     |                |
| sub_x_117          | DW01_sub         | apparch (area)     |                |
| add_x_118          | DW01_inc         | apparch (area)     |                |
| add_x_120          | DW01_inc         | apparch (area)     |                |
| lte_x_122          | DW_cmp           | apparch (area)     |                |
| lte_x_123          | DW_cmp           | apparch (area)     |                |
| lte_x_124          | DW_cmp           | apparch (area)     |                |
| sub_x_125          | DW01_sub         | apparch (area)     |                |
| sub_x_126          | DW01_sub         | apparch (area)     |                |
| add_x_127          | DW01_inc         | apparch (area)     |                |
| add_x_129          | DW01_inc         | apparch (area)     |                |
| lte_x_131          | DW_cmp           | apparch (area)     |                |
| lte_x_132          | DW_cmp           | apparch (area)     |                |
| lte_x_133          | DW_cmp           | apparch (area)     |                |
| sub_x_134          | DW01_sub         | apparch (area)     |                |
| sub_x_135          | DW01_sub         | apparch (area)     |                |
| add_x_136          | DW01_inc         | apparch (area)     |                |
| add_x_138          | DW01_inc         | apparch (area)     |                |
| lte_x_140          | DW_cmp           | apparch (area)     |                |
| lte_x_141          | DW_cmp           | apparch (area)     |                |
| lte_x_142          | DW_cmp           | apparch (area)     |                |
| sub_x_143          | DW01_sub         | apparch (area)     |                |
| sub_x_144          | DW01_sub         | apparch (area)     |                |
| add_x_145          | DW01_inc         | apparch (area)     |                |
| add_x_147          | DW01_inc         | apparch (area)     |                |
| lte_x_149          | DW_cmp           | apparch (area)     |                |
| lte_x_150          | DW_cmp           | apparch (area)     |                |
| lte_x_151          | DW_cmp           | apparch (area)     |                |
| sub_x_152          | DW01_sub         | apparch (area)     |                |
| sub_x_153          | DW01_sub         | apparch (area)     |                |
| add_x_154          | DW01_inc         | apparch (area)     |                |
| add_x_156          | DW01_inc         | apparch (area)     |                |
| lte_x_158          | DW_cmp           | apparch (area)     |                |
| lte_x_159          | DW_cmp           | apparch (area)     |                |
| lte_x_160          | DW_cmp           | apparch (area)     |                |
| sub_x_161          | DW01_sub         | apparch (area)     |                |
| sub_x_162          | DW01_sub         | apparch (area)     |                |
| add_x_163          | DW01_inc         | apparch (area)     |                |
| add_x_165          | DW01_inc         | apparch (area)     |                |
| lte_x_167          | DW_cmp           | apparch (area)     |                |
| lte_x_168          | DW_cmp           | apparch (area)     |                |
| lte_x_169          | DW_cmp           | apparch (area)     |                |
| sub_x_170          | DW01_sub         | apparch (area)     |                |
| sub_x_171          | DW01_sub         | apparch (area)     |                |
| add_x_172          | DW01_inc         | apparch (area)     |                |
| add_x_174          | DW01_inc         | apparch (area)     |                |
| lte_x_176          | DW_cmp           | apparch (area)     |                |
| lte_x_177          | DW_cmp           | apparch (area)     |                |
| lte_x_178          | DW_cmp           | apparch (area)     |                |
| sub_x_179          | DW01_sub         | apparch (area)     |                |
| sub_x_180          | DW01_sub         | apparch (area)     |                |
| add_x_181          | DW01_inc         | apparch (area)     |                |
| add_x_183          | DW01_inc         | apparch (area)     |                |
| lte_x_185          | DW_cmp           | apparch (area)     |                |
| lte_x_186          | DW_cmp           | apparch (area)     |                |
| lte_x_187          | DW_cmp           | apparch (area)     |                |
| sub_x_188          | DW01_sub         | apparch (area)     |                |
| sub_x_189          | DW01_sub         | apparch (area)     |                |
| add_x_190          | DW01_inc         | apparch (area)     |                |
| add_x_192          | DW01_inc         | apparch (area)     |                |
| lte_x_194          | DW_cmp           | apparch (area)     |                |
| lte_x_195          | DW_cmp           | apparch (area)     |                |
| lte_x_196          | DW_cmp           | apparch (area)     |                |
| sub_x_197          | DW01_sub         | apparch (area)     |                |
| sub_x_198          | DW01_sub         | apparch (area)     |                |
| add_x_199          | DW01_inc         | apparch (area)     |                |
| add_x_201          | DW01_inc         | apparch (area)     |                |
| lte_x_203          | DW_cmp           | apparch (area)     |                |
| lte_x_204          | DW_cmp           | apparch (area)     |                |
| lte_x_205          | DW_cmp           | apparch (area)     |                |
| sub_x_206          | DW01_sub         | apparch (area)     |                |
| sub_x_207          | DW01_sub         | apparch (area)     |                |
| add_x_208          | DW01_inc         | apparch (area)     |                |
| add_x_210          | DW01_inc         | apparch (area)     |                |
| lte_x_212          | DW_cmp           | apparch (area)     |                |
| lte_x_213          | DW_cmp           | apparch (area)     |                |
| lte_x_214          | DW_cmp           | apparch (area)     |                |
| sub_x_215          | DW01_sub         | apparch (area)     |                |
| sub_x_216          | DW01_sub         | apparch (area)     |                |
| add_x_217          | DW01_inc         | apparch (area)     |                |
| add_x_219          | DW01_inc         | apparch (area)     |                |
| lte_x_221          | DW_cmp           | apparch (area)     |                |
| lte_x_222          | DW_cmp           | apparch (area)     |                |
| lte_x_223          | DW_cmp           | apparch (area)     |                |
| sub_x_224          | DW01_sub         | apparch (area)     |                |
| sub_x_225          | DW01_sub         | apparch (area)     |                |
| add_x_226          | DW01_inc         | apparch (area)     |                |
| add_x_228          | DW01_inc         | apparch (area)     |                |
| lte_x_230          | DW_cmp           | apparch (area)     |                |
| lte_x_231          | DW_cmp           | apparch (area)     |                |
| lte_x_232          | DW_cmp           | apparch (area)     |                |
| sub_x_233          | DW01_sub         | apparch (area)     |                |
| sub_x_234          | DW01_sub         | apparch (area)     |                |
| add_x_235          | DW01_inc         | apparch (area)     |                |
| add_x_237          | DW01_inc         | apparch (area)     |                |
| lte_x_239          | DW_cmp           | apparch (area)     |                |
| lte_x_240          | DW_cmp           | apparch (area)     |                |
| lte_x_241          | DW_cmp           | apparch (area)     |                |
| sub_x_242          | DW01_sub         | apparch (area)     |                |
| sub_x_243          | DW01_sub         | apparch (area)     |                |
| add_x_244          | DW01_inc         | apparch (area)     |                |
| add_x_246          | DW01_inc         | apparch (area)     |                |
| lte_x_248          | DW_cmp           | apparch (area)     |                |
| lte_x_249          | DW_cmp           | apparch (area)     |                |
| lte_x_250          | DW_cmp           | apparch (area)     |                |
| sub_x_251          | DW01_sub         | apparch (area)     |                |
| sub_x_252          | DW01_sub         | apparch (area)     |                |
| add_x_253          | DW01_inc         | apparch (area)     |                |
| add_x_255          | DW01_inc         | apparch (area)     |                |
| lte_x_257          | DW_cmp           | apparch (area)     |                |
| lte_x_258          | DW_cmp           | apparch (area)     |                |
| lte_x_259          | DW_cmp           | apparch (area)     |                |
| sub_x_260          | DW01_sub         | apparch (area)     |                |
| sub_x_261          | DW01_sub         | apparch (area)     |                |
| add_x_262          | DW01_inc         | apparch (area)     |                |
| add_x_264          | DW01_inc         | apparch (area)     |                |
| lte_x_266          | DW_cmp           | apparch (area)     |                |
| lte_x_267          | DW_cmp           | apparch (area)     |                |
| lte_x_268          | DW_cmp           | apparch (area)     |                |
| sub_x_269          | DW01_sub         | apparch (area)     |                |
| sub_x_270          | DW01_sub         | apparch (area)     |                |
| add_x_271          | DW01_inc         | apparch (area)     |                |
| add_x_273          | DW01_inc         | apparch (area)     |                |
| lte_x_275          | DW_cmp           | apparch (area)     |                |
| lte_x_276          | DW_cmp           | apparch (area)     |                |
| lte_x_277          | DW_cmp           | apparch (area)     |                |
| sub_x_278          | DW01_sub         | apparch (area)     |                |
| sub_x_279          | DW01_sub         | apparch (area)     |                |
| add_x_280          | DW01_inc         | apparch (area)     |                |
| add_x_282          | DW01_inc         | apparch (area)     |                |
| lte_x_284          | DW_cmp           | apparch (area)     |                |
| lte_x_285          | DW_cmp           | apparch (area)     |                |
| lte_x_286          | DW_cmp           | apparch (area)     |                |
| sub_x_287          | DW01_sub         | apparch (area)     |                |
| sub_x_288          | DW01_sub         | apparch (area)     |                |
| add_x_289          | DW01_inc         | apparch (area)     |                |
| add_x_291          | DW01_inc         | apparch (area)     |                |
| lte_x_293          | DW_cmp           | apparch (area)     |                |
| lte_x_294          | DW_cmp           | apparch (area)     |                |
| lte_x_295          | DW_cmp           | apparch (area)     |                |
| sub_x_296          | DW01_sub         | apparch (area)     |                |
| sub_x_297          | DW01_sub         | apparch (area)     |                |
| add_x_298          | DW01_inc         | apparch (area)     |                |
| add_x_300          | DW01_inc         | apparch (area)     |                |
| lte_x_302          | DW_cmp           | apparch (area)     |                |
| lte_x_303          | DW_cmp           | apparch (area)     |                |
| lte_x_304          | DW_cmp           | apparch (area)     |                |
| sub_x_305          | DW01_sub         | apparch (area)     |                |
| sub_x_306          | DW01_sub         | apparch (area)     |                |
| add_x_307          | DW01_inc         | apparch (area)     |                |
| add_x_309          | DW01_inc         | apparch (area)     |                |
| lte_x_311          | DW_cmp           | apparch (area)     |                |
| lte_x_312          | DW_cmp           | apparch (area)     |                |
| lte_x_313          | DW_cmp           | apparch (area)     |                |
| sub_x_314          | DW01_sub         | apparch (area)     |                |
| sub_x_315          | DW01_sub         | apparch (area)     |                |
| add_x_316          | DW01_inc         | apparch (area)     |                |
| add_x_318          | DW01_inc         | apparch (area)     |                |
| lte_x_320          | DW_cmp           | apparch (area)     |                |
| lte_x_321          | DW_cmp           | apparch (area)     |                |
| lte_x_322          | DW_cmp           | apparch (area)     |                |
| sub_x_323          | DW01_sub         | apparch (area)     |                |
| sub_x_324          | DW01_sub         | apparch (area)     |                |
| add_x_325          | DW01_inc         | apparch (area)     |                |
| add_x_327          | DW01_inc         | apparch (area)     |                |
| lte_x_329          | DW_cmp           | apparch (area)     |                |
| lte_x_330          | DW_cmp           | apparch (area)     |                |
| lte_x_331          | DW_cmp           | apparch (area)     |                |
| sub_x_332          | DW01_sub         | apparch (area)     |                |
| sub_x_333          | DW01_sub         | apparch (area)     |                |
| add_x_334          | DW01_inc         | apparch (area)     |                |
| add_x_336          | DW01_inc         | apparch (area)     |                |
| lte_x_338          | DW_cmp           | apparch (area)     |                |
| lte_x_339          | DW_cmp           | apparch (area)     |                |
| lte_x_340          | DW_cmp           | apparch (area)     |                |
| sub_x_341          | DW01_sub         | apparch (area)     |                |
| sub_x_342          | DW01_sub         | apparch (area)     |                |
| add_x_343          | DW01_inc         | apparch (area)     |                |
| add_x_345          | DW01_inc         | apparch (area)     |                |
| lte_x_347          | DW_cmp           | apparch (area)     |                |
| lte_x_348          | DW_cmp           | apparch (area)     |                |
| lte_x_349          | DW_cmp           | apparch (area)     |                |
| sub_x_350          | DW01_sub         | apparch (area)     |                |
| sub_x_351          | DW01_sub         | apparch (area)     |                |
| add_x_352          | DW01_inc         | apparch (area)     |                |
| add_x_354          | DW01_inc         | apparch (area)     |                |
| lte_x_356          | DW_cmp           | apparch (area)     |                |
| lte_x_357          | DW_cmp           | apparch (area)     |                |
| lte_x_358          | DW_cmp           | apparch (area)     |                |
| sub_x_359          | DW01_sub         | apparch (area)     |                |
| sub_x_360          | DW01_sub         | apparch (area)     |                |
| add_x_361          | DW01_inc         | apparch (area)     |                |
| add_x_363          | DW01_inc         | apparch (area)     |                |
| lte_x_365          | DW_cmp           | apparch (area)     |                |
| lte_x_366          | DW_cmp           | apparch (area)     |                |
| lte_x_367          | DW_cmp           | apparch (area)     |                |
| sub_x_368          | DW01_sub         | apparch (area)     |                |
| sub_x_369          | DW01_sub         | apparch (area)     |                |
| add_x_370          | DW01_inc         | apparch (area)     |                |
| add_x_372          | DW01_inc         | apparch (area)     |                |
| lte_x_374          | DW_cmp           | apparch (area)     |                |
| lte_x_375          | DW_cmp           | apparch (area)     |                |
| lte_x_376          | DW_cmp           | apparch (area)     |                |
| sub_x_377          | DW01_sub         | apparch (area)     |                |
| sub_x_378          | DW01_sub         | apparch (area)     |                |
| add_x_379          | DW01_inc         | apparch (area)     |                |
| add_x_381          | DW01_inc         | apparch (area)     |                |
| lte_x_383          | DW_cmp           | apparch (area)     |                |
| lte_x_384          | DW_cmp           | apparch (area)     |                |
| lte_x_385          | DW_cmp           | apparch (area)     |                |
| sub_x_386          | DW01_sub         | apparch (area)     |                |
| sub_x_387          | DW01_sub         | apparch (area)     |                |
| add_x_388          | DW01_inc         | apparch (area)     |                |
| add_x_390          | DW01_inc         | apparch (area)     |                |
| lte_x_392          | DW_cmp           | apparch (area)     |                |
| lte_x_393          | DW_cmp           | apparch (area)     |                |
| lte_x_394          | DW_cmp           | apparch (area)     |                |
| lte_x_395          | DW_cmp           | apparch (area)     |                |
| lte_x_396          | DW_cmp           | apparch (area)     |                |
| lte_x_397          | DW_cmp           | apparch (area)     |                |
| lte_x_398          | DW_cmp           | apparch (area)     |                |
| lte_x_399          | DW_cmp           | apparch (area)     |                |
| lte_x_400          | DW_cmp           | apparch (area)     |                |
| lte_x_401          | DW_cmp           | apparch (area)     |                |
| lte_x_402          | DW_cmp           | apparch (area)     |                |
| lte_x_403          | DW_cmp           | apparch (area)     |                |
| lte_x_404          | DW_cmp           | apparch (area)     |                |
| lte_x_405          | DW_cmp           | apparch (area)     |                |
| lte_x_406          | DW_cmp           | apparch (area)     |                |
| lte_x_407          | DW_cmp           | apparch (area)     |                |
| lte_x_408          | DW_cmp           | apparch (area)     |                |
| lte_x_409          | DW_cmp           | apparch (area)     |                |
| lte_x_410          | DW_cmp           | apparch (area)     |                |
| lte_x_411          | DW_cmp           | apparch (area)     |                |
| lte_x_412          | DW_cmp           | apparch (area)     |                |
| lte_x_413          | DW_cmp           | apparch (area)     |                |
| lte_x_414          | DW_cmp           | apparch (area)     |                |
| lte_x_415          | DW_cmp           | apparch (area)     |                |
| lte_x_416          | DW_cmp           | apparch (area)     |                |
| lte_x_417          | DW_cmp           | apparch (area)     |                |
| lte_x_418          | DW_cmp           | apparch (area)     |                |
| lte_x_419          | DW_cmp           | apparch (area)     |                |
| lte_x_420          | DW_cmp           | apparch (area)     |                |
| lte_x_421          | DW_cmp           | apparch (area)     |                |
| lte_x_422          | DW_cmp           | apparch (area)     |                |
| lte_x_423          | DW_cmp           | apparch (area)     |                |
| lte_x_424          | DW_cmp           | apparch (area)     |                |
| lte_x_425          | DW_cmp           | apparch (area)     |                |
| lte_x_426          | DW_cmp           | apparch (area)     |                |
| lte_x_427          | DW_cmp           | apparch (area)     |                |
| lte_x_428          | DW_cmp           | apparch (area)     |                |
| lte_x_429          | DW_cmp           | apparch (area)     |                |
| lte_x_430          | DW_cmp           | apparch (area)     |                |
| lte_x_431          | DW_cmp           | apparch (area)     |                |
| lte_x_432          | DW_cmp           | apparch (area)     |                |
| lte_x_433          | DW_cmp           | apparch (area)     |                |
| lte_x_434          | DW_cmp           | apparch (area)     |                |
| DP_OP_839J1_122_8998                  |                    |                |
|                    | DP_OP_839J1_122_8998 | str (area,speed)                |
| DP_OP_843J1_123_5647                  |                    |                |
|                    | DP_OP_843J1_123_5647 | str (area)     |                |
===============================================================================

1
