###################################################################

# Created by write_sdc on Sun Jan 26 14:35:05 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions slow -library slow
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 1 [get_ports so_data]
set_load -pin_load 1 [get_ports so_valid]
set_load -pin_load 1 [get_ports oem_finish]
set_load -pin_load 1 [get_ports odd1_wr]
set_load -pin_load 1 [get_ports odd2_wr]
set_load -pin_load 1 [get_ports odd3_wr]
set_load -pin_load 1 [get_ports odd4_wr]
set_load -pin_load 1 [get_ports even1_wr]
set_load -pin_load 1 [get_ports even2_wr]
set_load -pin_load 1 [get_ports even3_wr]
set_load -pin_load 1 [get_ports even4_wr]
set_load -pin_load 1 [get_ports {oem_addr[4]}]
set_load -pin_load 1 [get_ports {oem_addr[3]}]
set_load -pin_load 1 [get_ports {oem_addr[2]}]
set_load -pin_load 1 [get_ports {oem_addr[1]}]
set_load -pin_load 1 [get_ports {oem_addr[0]}]
set_load -pin_load 1 [get_ports {oem_dataout[7]}]
set_load -pin_load 1 [get_ports {oem_dataout[6]}]
set_load -pin_load 1 [get_ports {oem_dataout[5]}]
set_load -pin_load 1 [get_ports {oem_dataout[4]}]
set_load -pin_load 1 [get_ports {oem_dataout[3]}]
set_load -pin_load 1 [get_ports {oem_dataout[2]}]
set_load -pin_load 1 [get_ports {oem_dataout[1]}]
set_load -pin_load 1 [get_ports {oem_dataout[0]}]
set_max_fanout 20 [get_ports clk]
set_max_fanout 20 [get_ports reset]
set_max_fanout 20 [get_ports load]
set_max_fanout 20 [get_ports pi_msb]
set_max_fanout 20 [get_ports pi_low]
set_max_fanout 20 [get_ports pi_end]
set_max_fanout 20 [get_ports {pi_data[15]}]
set_max_fanout 20 [get_ports {pi_data[14]}]
set_max_fanout 20 [get_ports {pi_data[13]}]
set_max_fanout 20 [get_ports {pi_data[12]}]
set_max_fanout 20 [get_ports {pi_data[11]}]
set_max_fanout 20 [get_ports {pi_data[10]}]
set_max_fanout 20 [get_ports {pi_data[9]}]
set_max_fanout 20 [get_ports {pi_data[8]}]
set_max_fanout 20 [get_ports {pi_data[7]}]
set_max_fanout 20 [get_ports {pi_data[6]}]
set_max_fanout 20 [get_ports {pi_data[5]}]
set_max_fanout 20 [get_ports {pi_data[4]}]
set_max_fanout 20 [get_ports {pi_data[3]}]
set_max_fanout 20 [get_ports {pi_data[2]}]
set_max_fanout 20 [get_ports {pi_data[1]}]
set_max_fanout 20 [get_ports {pi_data[0]}]
set_max_fanout 20 [get_ports {pi_length[1]}]
set_max_fanout 20 [get_ports {pi_length[0]}]
set_max_fanout 20 [get_ports pi_fill]
create_clock [get_ports clk]  -period 15  -waveform {0 7.5}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty 0.1  [get_clocks clk]
set_input_delay -clock clk  7.5  [get_ports reset]
set_input_delay -clock clk  7.5  [get_ports load]
set_input_delay -clock clk  7.5  [get_ports pi_msb]
set_input_delay -clock clk  7.5  [get_ports pi_low]
set_input_delay -clock clk  7.5  [get_ports pi_end]
set_input_delay -clock clk  7.5  [get_ports {pi_data[15]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[14]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[13]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[12]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[11]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[10]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[9]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[8]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[7]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[6]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[5]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[4]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[3]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[2]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[1]}]
set_input_delay -clock clk  7.5  [get_ports {pi_data[0]}]
set_input_delay -clock clk  7.5  [get_ports {pi_length[1]}]
set_input_delay -clock clk  7.5  [get_ports {pi_length[0]}]
set_input_delay -clock clk  7.5  [get_ports pi_fill]
set_output_delay -clock clk  0.5  [get_ports so_data]
set_output_delay -clock clk  0.5  [get_ports so_valid]
set_output_delay -clock clk  0.5  [get_ports oem_finish]
set_output_delay -clock clk  0.5  [get_ports odd1_wr]
set_output_delay -clock clk  0.5  [get_ports odd2_wr]
set_output_delay -clock clk  0.5  [get_ports odd3_wr]
set_output_delay -clock clk  0.5  [get_ports odd4_wr]
set_output_delay -clock clk  0.5  [get_ports even1_wr]
set_output_delay -clock clk  0.5  [get_ports even2_wr]
set_output_delay -clock clk  0.5  [get_ports even3_wr]
set_output_delay -clock clk  0.5  [get_ports even4_wr]
set_output_delay -clock clk  0.5  [get_ports {oem_addr[4]}]
set_output_delay -clock clk  0.5  [get_ports {oem_addr[3]}]
set_output_delay -clock clk  0.5  [get_ports {oem_addr[2]}]
set_output_delay -clock clk  0.5  [get_ports {oem_addr[1]}]
set_output_delay -clock clk  0.5  [get_ports {oem_addr[0]}]
set_output_delay -clock clk  0.5  [get_ports {oem_dataout[7]}]
set_output_delay -clock clk  0.5  [get_ports {oem_dataout[6]}]
set_output_delay -clock clk  0.5  [get_ports {oem_dataout[5]}]
set_output_delay -clock clk  0.5  [get_ports {oem_dataout[4]}]
set_output_delay -clock clk  0.5  [get_ports {oem_dataout[3]}]
set_output_delay -clock clk  0.5  [get_ports {oem_dataout[2]}]
set_output_delay -clock clk  0.5  [get_ports {oem_dataout[1]}]
set_output_delay -clock clk  0.5  [get_ports {oem_dataout[0]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports reset]
set_drive 1  [get_ports load]
set_drive 1  [get_ports pi_msb]
set_drive 1  [get_ports pi_low]
set_drive 1  [get_ports pi_end]
set_drive 1  [get_ports {pi_data[15]}]
set_drive 1  [get_ports {pi_data[14]}]
set_drive 1  [get_ports {pi_data[13]}]
set_drive 1  [get_ports {pi_data[12]}]
set_drive 1  [get_ports {pi_data[11]}]
set_drive 1  [get_ports {pi_data[10]}]
set_drive 1  [get_ports {pi_data[9]}]
set_drive 1  [get_ports {pi_data[8]}]
set_drive 1  [get_ports {pi_data[7]}]
set_drive 1  [get_ports {pi_data[6]}]
set_drive 1  [get_ports {pi_data[5]}]
set_drive 1  [get_ports {pi_data[4]}]
set_drive 1  [get_ports {pi_data[3]}]
set_drive 1  [get_ports {pi_data[2]}]
set_drive 1  [get_ports {pi_data[1]}]
set_drive 1  [get_ports {pi_data[0]}]
set_drive 1  [get_ports {pi_length[1]}]
set_drive 1  [get_ports {pi_length[0]}]
set_drive 1  [get_ports pi_fill]
