###################################################################

# Created by write_sdc on Sun Jan 26 15:07:14 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max slow -max_library slow\
                         -min fast -min_library fast
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 1 [get_ports IROM_rd]
set_load -pin_load 1 [get_ports {IROM_A[5]}]
set_load -pin_load 1 [get_ports {IROM_A[4]}]
set_load -pin_load 1 [get_ports {IROM_A[3]}]
set_load -pin_load 1 [get_ports {IROM_A[2]}]
set_load -pin_load 1 [get_ports {IROM_A[1]}]
set_load -pin_load 1 [get_ports {IROM_A[0]}]
set_load -pin_load 1 [get_ports IRAM_valid]
set_load -pin_load 1 [get_ports {IRAM_D[7]}]
set_load -pin_load 1 [get_ports {IRAM_D[6]}]
set_load -pin_load 1 [get_ports {IRAM_D[5]}]
set_load -pin_load 1 [get_ports {IRAM_D[4]}]
set_load -pin_load 1 [get_ports {IRAM_D[3]}]
set_load -pin_load 1 [get_ports {IRAM_D[2]}]
set_load -pin_load 1 [get_ports {IRAM_D[1]}]
set_load -pin_load 1 [get_ports {IRAM_D[0]}]
set_load -pin_load 1 [get_ports {IRAM_A[5]}]
set_load -pin_load 1 [get_ports {IRAM_A[4]}]
set_load -pin_load 1 [get_ports {IRAM_A[3]}]
set_load -pin_load 1 [get_ports {IRAM_A[2]}]
set_load -pin_load 1 [get_ports {IRAM_A[1]}]
set_load -pin_load 1 [get_ports {IRAM_A[0]}]
set_load -pin_load 1 [get_ports busy]
set_load -pin_load 1 [get_ports done]
set_max_fanout 20 [get_ports clk]
set_max_fanout 20 [get_ports reset]
set_max_fanout 20 [get_ports {cmd[3]}]
set_max_fanout 20 [get_ports {cmd[2]}]
set_max_fanout 20 [get_ports {cmd[1]}]
set_max_fanout 20 [get_ports {cmd[0]}]
set_max_fanout 20 [get_ports cmd_valid]
set_max_fanout 20 [get_ports {IROM_Q[7]}]
set_max_fanout 20 [get_ports {IROM_Q[6]}]
set_max_fanout 20 [get_ports {IROM_Q[5]}]
set_max_fanout 20 [get_ports {IROM_Q[4]}]
set_max_fanout 20 [get_ports {IROM_Q[3]}]
set_max_fanout 20 [get_ports {IROM_Q[2]}]
set_max_fanout 20 [get_ports {IROM_Q[1]}]
set_max_fanout 20 [get_ports {IROM_Q[0]}]
create_clock [get_ports clk]  -period 15  -waveform {0 7.5}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty 0.1  [get_clocks clk]
set_input_delay -clock clk  7.5  [get_ports reset]
set_input_delay -clock clk  7.5  [get_ports {cmd[3]}]
set_input_delay -clock clk  7.5  [get_ports {cmd[2]}]
set_input_delay -clock clk  7.5  [get_ports {cmd[1]}]
set_input_delay -clock clk  7.5  [get_ports {cmd[0]}]
set_input_delay -clock clk  7.5  [get_ports cmd_valid]
set_input_delay -clock clk  7.5  [get_ports {IROM_Q[7]}]
set_input_delay -clock clk  7.5  [get_ports {IROM_Q[6]}]
set_input_delay -clock clk  7.5  [get_ports {IROM_Q[5]}]
set_input_delay -clock clk  7.5  [get_ports {IROM_Q[4]}]
set_input_delay -clock clk  7.5  [get_ports {IROM_Q[3]}]
set_input_delay -clock clk  7.5  [get_ports {IROM_Q[2]}]
set_input_delay -clock clk  7.5  [get_ports {IROM_Q[1]}]
set_input_delay -clock clk  7.5  [get_ports {IROM_Q[0]}]
set_output_delay -clock clk  0.5  [get_ports IROM_rd]
set_output_delay -clock clk  0.5  [get_ports {IROM_A[5]}]
set_output_delay -clock clk  0.5  [get_ports {IROM_A[4]}]
set_output_delay -clock clk  0.5  [get_ports {IROM_A[3]}]
set_output_delay -clock clk  0.5  [get_ports {IROM_A[2]}]
set_output_delay -clock clk  0.5  [get_ports {IROM_A[1]}]
set_output_delay -clock clk  0.5  [get_ports {IROM_A[0]}]
set_output_delay -clock clk  0.5  [get_ports IRAM_valid]
set_output_delay -clock clk  0.5  [get_ports {IRAM_D[7]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_D[6]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_D[5]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_D[4]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_D[3]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_D[2]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_D[1]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_D[0]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_A[5]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_A[4]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_A[3]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_A[2]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_A[1]}]
set_output_delay -clock clk  0.5  [get_ports {IRAM_A[0]}]
set_output_delay -clock clk  0.5  [get_ports busy]
set_output_delay -clock clk  0.5  [get_ports done]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports reset]
set_drive 1  [get_ports {cmd[3]}]
set_drive 1  [get_ports {cmd[2]}]
set_drive 1  [get_ports {cmd[1]}]
set_drive 1  [get_ports {cmd[0]}]
set_drive 1  [get_ports cmd_valid]
set_drive 1  [get_ports {IROM_Q[7]}]
set_drive 1  [get_ports {IROM_Q[6]}]
set_drive 1  [get_ports {IROM_Q[5]}]
set_drive 1  [get_ports {IROM_Q[4]}]
set_drive 1  [get_ports {IROM_Q[3]}]
set_drive 1  [get_ports {IROM_Q[2]}]
set_drive 1  [get_ports {IROM_Q[1]}]
set_drive 1  [get_ports {IROM_Q[0]}]
