 
****************************************
Report : resources
Design : huffman
Version: U-2022.12
Date   : Mon Jan 27 23:53:48 2025
****************************************


Resource Report for this hierarchy in file ./huffman.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| add_x_8        | DW01_inc       | width=7    | add_116 (huffman.v:116)    |
| add_x_9        | DW01_inc       | width=7    | add_117 (huffman.v:117)    |
| add_x_10       | DW01_inc       | width=7    | add_118 (huffman.v:118)    |
| add_x_11       | DW01_inc       | width=7    | add_119 (huffman.v:119)    |
| add_x_12       | DW01_inc       | width=7    | add_120 (huffman.v:120)    |
| add_x_13       | DW01_inc       | width=7    | add_121 (huffman.v:121)    |
| add_x_14       | DW01_add       | width=7    | add_136 (huffman.v:136)    |
| add_x_22       | DW01_inc       | width=3    | add_261 (huffman.v:261)    |
| add_x_25       | DW01_inc       | width=3    | add_273 (huffman.v:273)    |
=============================================================================


Resource Report for Ungrouped Hierarchy SORT_inst in file ./huffman.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| add_x_13       | DW01_inc       | width=3    | add_392 (huffman.v:392)    |
| gt_x_16        | DW_cmp         | width=7    | gt_415 (huffman.v:415)     |
| gt_x_17        | DW_cmp         | width=7    | gt_416 (huffman.v:416)     |
| gt_x_18        | DW_cmp         | width=7    | gt_417 (huffman.v:417)     |
| lt_x_19        | DW_cmp         | width=7    | lt_418 (huffman.v:418)     |
| lt_x_20        | DW_cmp         | width=7    | lt_419 (huffman.v:419)     |
| lt_x_21        | DW_cmp         | width=7    | lt_420 (huffman.v:420)     |
| eq_x_22        | DW_cmp         | width=7    | eq_497_C422 (huffman.v:497) |
| lt_x_23        | DW_cmp         | width=4    | lt_497_C422 (huffman.v:497) |
| eq_x_24        | DW_cmp         | width=7    | eq_497_C423 (huffman.v:497) |
| lt_x_25        | DW_cmp         | width=4    | lt_497_C423 (huffman.v:497) |
| eq_x_26        | DW_cmp         | width=7    | eq_497_C424 (huffman.v:497) |
| lt_x_27        | DW_cmp         | width=4    | lt_497_C424 (huffman.v:497) |
| lt_x_28        | DW_cmp         | width=7    | lt_448 (huffman.v:448)     |
| lt_x_29        | DW_cmp         | width=7    | lt_450 (huffman.v:450)     |
| lt_x_30        | DW_cmp         | width=7    | lt_461 (huffman.v:461)     |
| lt_x_31        | DW_cmp         | width=7    | lt_463 (huffman.v:463)     |
| lt_x_32        | DW_cmp         | width=7    | lt_465 (huffman.v:465)     |
| gt_x_88        | DW_cmp         | width=7    | gt_431 (huffman.v:431)     |
|                |                |            | gt_476 (huffman.v:476)     |
|                |                |            | gt_497_C438 (huffman.v:497) |
                |                |            | gt_497_C439 (huffman.v:497) |
                |                |            | gt_497_C483 (huffman.v:497) |
                |                |            | gt_497_C484 (huffman.v:497) |
| lt_x_89        | DW_cmp         | width=7    | lt_432 (huffman.v:432)     |
|                |                |            | lt_477 (huffman.v:477)     |
| eq_x_90        | DW_cmp         | width=7    | eq_497_C438 (huffman.v:497) |
                |                |            | eq_497_C439 (huffman.v:497) |
                |                |            | eq_497_C483 (huffman.v:497) |
                |                |            | eq_497_C484 (huffman.v:497) |
| gt_x_91        | DW_cmp         | width=7    | gt_433 (huffman.v:433)     |
|                |                |            | gt_478 (huffman.v:478)     |
|                |                |            | gt_497_C440 (huffman.v:497) |
                |                |            | gt_497_C441 (huffman.v:497) |
                |                |            | gt_497_C485 (huffman.v:497) |
                |                |            | gt_497_C486 (huffman.v:497) |
| lt_x_92        | DW_cmp         | width=7    | lt_434 (huffman.v:434)     |
|                |                |            | lt_479 (huffman.v:479)     |
| eq_x_93        | DW_cmp         | width=7    | eq_497_C440 (huffman.v:497) |
                |                |            | eq_497_C441 (huffman.v:497) |
                |                |            | eq_497_C485 (huffman.v:497) |
                |                |            | eq_497_C486 (huffman.v:497) |
| lt_x_94        | DW_cmp         | width=4    | lt_497_C438 (huffman.v:497) |
                |                |            | lt_497_C439 (huffman.v:497) |
                |                |            | lt_497_C483 (huffman.v:497) |
                |                |            | lt_497_C484 (huffman.v:497) |
| lt_x_95        | DW_cmp         | width=4    | lt_497_C440 (huffman.v:497) |
                |                |            | lt_497_C441 (huffman.v:497) |
                |                |            | lt_497_C485 (huffman.v:497) |
                |                |            | lt_497_C486 (huffman.v:497) |
| gt_x_96        | DW_cmp         | width=7    | gt_445 (huffman.v:445)     |
|                |                |            | gt_497_C452 (huffman.v:497) |
                |                |            | gt_497_C455 (huffman.v:497) |
| eq_x_97        | DW_cmp         | width=7    | eq_497_C452 (huffman.v:497) |
                |                |            | eq_497_C455 (huffman.v:497) |
| gt_x_98        | DW_cmp         | width=7    | gt_447 (huffman.v:447)     |
|                |                |            | gt_497_C454 (huffman.v:497) |
                |                |            | gt_497_C457 (huffman.v:497) |
| eq_x_99        | DW_cmp         | width=7    | eq_497_C454 (huffman.v:497) |
                |                |            | eq_497_C457 (huffman.v:497) |
| lt_x_100       | DW_cmp         | width=4    | lt_497_C452 (huffman.v:497) |
                |                |            | lt_497_C455 (huffman.v:497) |
| lt_x_101       | DW_cmp         | width=4    | lt_497_C454 (huffman.v:497) |
                |                |            | lt_497_C457 (huffman.v:497) |
| gt_x_102       | DW_cmp         | width=7    | gt_460 (huffman.v:460)     |
|                |                |            | gt_497_C467 (huffman.v:497) |
                |                |            | gt_497_C468 (huffman.v:497) |
| eq_x_103       | DW_cmp         | width=7    | eq_497_C467 (huffman.v:497) |
                |                |            | eq_497_C468 (huffman.v:497) |
| gt_x_104       | DW_cmp         | width=7    | gt_462 (huffman.v:462)     |
|                |                |            | gt_497_C469 (huffman.v:497) |
                |                |            | gt_497_C470 (huffman.v:497) |
| eq_x_105       | DW_cmp         | width=7    | eq_497_C469 (huffman.v:497) |
                |                |            | eq_497_C470 (huffman.v:497) |
| gt_x_106       | DW_cmp         | width=7    | gt_464 (huffman.v:464)     |
|                |                |            | gt_497_C471 (huffman.v:497) |
                |                |            | gt_497_C472 (huffman.v:497) |
| eq_x_107       | DW_cmp         | width=7    | eq_497_C471 (huffman.v:497) |
                |                |            | eq_497_C472 (huffman.v:497) |
| lt_x_108       | DW_cmp         | width=4    | lt_497_C467 (huffman.v:497) |
                |                |            | lt_497_C468 (huffman.v:497) |
| lt_x_109       | DW_cmp         | width=4    | lt_497_C469 (huffman.v:497) |
                |                |            | lt_497_C470 (huffman.v:497) |
| lt_x_110       | DW_cmp         | width=4    | lt_497_C471 (huffman.v:497) |
                |                |            | lt_497_C472 (huffman.v:497) |
=============================================================================


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| add_x_8            | DW01_inc         | apparch (area)     |                |
| add_x_9            | DW01_inc         | apparch (area)     |                |
| add_x_10           | DW01_inc         | apparch (area)     |                |
| add_x_11           | DW01_inc         | apparch (area)     |                |
| add_x_12           | DW01_inc         | apparch (area)     |                |
| add_x_13           | DW01_inc         | apparch (area)     |                |
| add_x_14           | DW01_add         | apparch (area)     |                |
| add_x_22           | DW01_inc         | apparch (area)     |                |
| add_x_25           | DW01_inc         | apparch (area)     |                |
| add_x_13           | DW01_inc         | apparch (area)     |                |
| gt_x_16            | DW_cmp           | apparch (area)     |                |
| gt_x_17            | DW_cmp           | apparch (area)     |                |
| gt_x_18            | DW_cmp           | apparch (area)     |                |
| lt_x_19            | DW_cmp           | apparch (area)     |                |
| lt_x_20            | DW_cmp           | apparch (area)     |                |
| lt_x_21            | DW_cmp           | apparch (area)     |                |
| eq_x_22            | DW_cmp           | apparch (area)     |                |
| lt_x_23            | DW_cmp           | apparch (area)     |                |
| eq_x_24            | DW_cmp           | apparch (area)     |                |
| lt_x_25            | DW_cmp           | apparch (area)     |                |
| eq_x_26            | DW_cmp           | apparch (area)     |                |
| lt_x_27            | DW_cmp           | apparch (area)     |                |
| lt_x_28            | DW_cmp           | apparch (area)     |                |
| lt_x_29            | DW_cmp           | apparch (area)     |                |
| lt_x_30            | DW_cmp           | apparch (area)     |                |
| lt_x_31            | DW_cmp           | apparch (area)     |                |
| lt_x_32            | DW_cmp           | apparch (area)     |                |
| gt_x_88            | DW_cmp           | apparch (area)     |                |
| lt_x_89            | DW_cmp           | apparch (area)     |                |
| eq_x_90            | DW_cmp           | apparch (area)     |                |
| gt_x_91            | DW_cmp           | apparch (area)     |                |
| lt_x_92            | DW_cmp           | apparch (area)     |                |
| eq_x_93            | DW_cmp           | apparch (area)     |                |
| lt_x_94            | DW_cmp           | apparch (area)     |                |
| lt_x_95            | DW_cmp           | apparch (area)     |                |
| gt_x_96            | DW_cmp           | apparch (area)     |                |
| eq_x_97            | DW_cmp           | apparch (area)     |                |
| gt_x_98            | DW_cmp           | apparch (area)     |                |
| eq_x_99            | DW_cmp           | apparch (area)     |                |
| lt_x_100           | DW_cmp           | apparch (area)     |                |
| lt_x_101           | DW_cmp           | apparch (area)     |                |
| gt_x_102           | DW_cmp           | apparch (area)     |                |
| eq_x_103           | DW_cmp           | apparch (area)     |                |
| gt_x_104           | DW_cmp           | apparch (area)     |                |
| eq_x_105           | DW_cmp           | apparch (area)     |                |
| gt_x_106           | DW_cmp           | apparch (area)     |                |
| eq_x_107           | DW_cmp           | apparch (area)     |                |
| lt_x_108           | DW_cmp           | apparch (area)     |                |
| lt_x_109           | DW_cmp           | apparch (area)     |                |
| lt_x_110           | DW_cmp           | apparch (area)     |                |
===============================================================================

1
