###################################################################

# Created by write_sdc on Thu Jan 30 23:07:15 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions slow -library slow
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 1 [get_ports valid]
set_load -pin_load 1 [get_ports is_inside]
set_max_fanout 20 [get_ports clk]
set_max_fanout 20 [get_ports reset]
set_max_fanout 20 [get_ports {X[9]}]
set_max_fanout 20 [get_ports {X[8]}]
set_max_fanout 20 [get_ports {X[7]}]
set_max_fanout 20 [get_ports {X[6]}]
set_max_fanout 20 [get_ports {X[5]}]
set_max_fanout 20 [get_ports {X[4]}]
set_max_fanout 20 [get_ports {X[3]}]
set_max_fanout 20 [get_ports {X[2]}]
set_max_fanout 20 [get_ports {X[1]}]
set_max_fanout 20 [get_ports {X[0]}]
set_max_fanout 20 [get_ports {Y[9]}]
set_max_fanout 20 [get_ports {Y[8]}]
set_max_fanout 20 [get_ports {Y[7]}]
set_max_fanout 20 [get_ports {Y[6]}]
set_max_fanout 20 [get_ports {Y[5]}]
set_max_fanout 20 [get_ports {Y[4]}]
set_max_fanout 20 [get_ports {Y[3]}]
set_max_fanout 20 [get_ports {Y[2]}]
set_max_fanout 20 [get_ports {Y[1]}]
set_max_fanout 20 [get_ports {Y[0]}]
set_max_fanout 20 [get_ports {R[10]}]
set_max_fanout 20 [get_ports {R[9]}]
set_max_fanout 20 [get_ports {R[8]}]
set_max_fanout 20 [get_ports {R[7]}]
set_max_fanout 20 [get_ports {R[6]}]
set_max_fanout 20 [get_ports {R[5]}]
set_max_fanout 20 [get_ports {R[4]}]
set_max_fanout 20 [get_ports {R[3]}]
set_max_fanout 20 [get_ports {R[2]}]
set_max_fanout 20 [get_ports {R[1]}]
set_max_fanout 20 [get_ports {R[0]}]
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -period 50  -waveform {0 25}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty 0.1  [get_clocks clk]
set_input_delay -clock clk  -clock_fall  0  [get_ports reset]
set_input_delay -clock clk  -clock_fall  0  [get_ports {X[9]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {X[8]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {X[7]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {X[6]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {X[5]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {X[4]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {X[3]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {X[2]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {X[1]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {X[0]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {Y[9]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {Y[8]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {Y[7]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {Y[6]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {Y[5]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {Y[4]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {Y[3]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {Y[2]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {Y[1]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {Y[0]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {R[10]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {R[9]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {R[8]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {R[7]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {R[6]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {R[5]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {R[4]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {R[3]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {R[2]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {R[1]}]
set_input_delay -clock clk  -clock_fall  0  [get_ports {R[0]}]
set_output_delay -clock clk  -clock_fall  0  [get_ports valid]
set_output_delay -clock clk  -clock_fall  0  [get_ports is_inside]
set_drive 0.1  [get_ports clk]
set_drive 0.1  [get_ports reset]
set_drive 0.1  [get_ports {X[9]}]
set_drive 0.1  [get_ports {X[8]}]
set_drive 0.1  [get_ports {X[7]}]
set_drive 0.1  [get_ports {X[6]}]
set_drive 0.1  [get_ports {X[5]}]
set_drive 0.1  [get_ports {X[4]}]
set_drive 0.1  [get_ports {X[3]}]
set_drive 0.1  [get_ports {X[2]}]
set_drive 0.1  [get_ports {X[1]}]
set_drive 0.1  [get_ports {X[0]}]
set_drive 0.1  [get_ports {Y[9]}]
set_drive 0.1  [get_ports {Y[8]}]
set_drive 0.1  [get_ports {Y[7]}]
set_drive 0.1  [get_ports {Y[6]}]
set_drive 0.1  [get_ports {Y[5]}]
set_drive 0.1  [get_ports {Y[4]}]
set_drive 0.1  [get_ports {Y[3]}]
set_drive 0.1  [get_ports {Y[2]}]
set_drive 0.1  [get_ports {Y[1]}]
set_drive 0.1  [get_ports {Y[0]}]
set_drive 0.1  [get_ports {R[10]}]
set_drive 0.1  [get_ports {R[9]}]
set_drive 0.1  [get_ports {R[8]}]
set_drive 0.1  [get_ports {R[7]}]
set_drive 0.1  [get_ports {R[6]}]
set_drive 0.1  [get_ports {R[5]}]
set_drive 0.1  [get_ports {R[4]}]
set_drive 0.1  [get_ports {R[3]}]
set_drive 0.1  [get_ports {R[2]}]
set_drive 0.1  [get_ports {R[1]}]
set_drive 0.1  [get_ports {R[0]}]
