 
****************************************
Report : resources
Design : STI_DAC
Version: U-2022.12
Date   : Sun Jan 26 14:35:05 2025
****************************************


Resource Report for this hierarchy in file ./STI_DAC.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| sub_x_1        | DW01_sub       | width=5    | STI_inst/sub_84 (STI_DAC.v:84) |
| eq_x_2         | DW_cmp         | width=5    | STI_inst/eq_86 (STI_DAC.v:86) |
| add_x_13       | DW01_inc       | width=5    | STI_inst/add_148 (STI_DAC.v:148) |
| add_x_18       | DW01_inc       | width=3    | DAC_inst/add_266 (STI_DAC.v:266) |
| add_x_19       | DW01_inc       | width=5    | DAC_inst/add_296 (STI_DAC.v:296) |
| add_x_20       | DW01_inc       | width=2    | DAC_inst/add_323 (STI_DAC.v:323) |
=============================================================================


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| sub_x_1            | DW01_sub         | apparch (area)     |                |
| eq_x_2             | DW_cmp           | apparch (area)     |                |
| add_x_13           | DW01_inc         | apparch (area)     |                |
| add_x_18           | DW01_inc         | apparch (area)     |                |
| add_x_19           | DW01_inc         | apparch (area)     |                |
| add_x_20           | DW01_inc         | apparch (area)     |                |
===============================================================================

1
