###################################################################

# Created by write_sdc on Sun Jan 26 01:16:27 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max slow -max_library slow\
                         -min fast -min_library fast
set_wire_load_mode top
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 1 [get_ports fir_valid]
set_load -pin_load 1 [get_ports fft_valid]
set_load -pin_load 1 [get_ports {fir_d[15]}]
set_load -pin_load 1 [get_ports {fir_d[14]}]
set_load -pin_load 1 [get_ports {fir_d[13]}]
set_load -pin_load 1 [get_ports {fir_d[12]}]
set_load -pin_load 1 [get_ports {fir_d[11]}]
set_load -pin_load 1 [get_ports {fir_d[10]}]
set_load -pin_load 1 [get_ports {fir_d[9]}]
set_load -pin_load 1 [get_ports {fir_d[8]}]
set_load -pin_load 1 [get_ports {fir_d[7]}]
set_load -pin_load 1 [get_ports {fir_d[6]}]
set_load -pin_load 1 [get_ports {fir_d[5]}]
set_load -pin_load 1 [get_ports {fir_d[4]}]
set_load -pin_load 1 [get_ports {fir_d[3]}]
set_load -pin_load 1 [get_ports {fir_d[2]}]
set_load -pin_load 1 [get_ports {fir_d[1]}]
set_load -pin_load 1 [get_ports {fir_d[0]}]
set_load -pin_load 1 [get_ports {fft_d1[31]}]
set_load -pin_load 1 [get_ports {fft_d1[30]}]
set_load -pin_load 1 [get_ports {fft_d1[29]}]
set_load -pin_load 1 [get_ports {fft_d1[28]}]
set_load -pin_load 1 [get_ports {fft_d1[27]}]
set_load -pin_load 1 [get_ports {fft_d1[26]}]
set_load -pin_load 1 [get_ports {fft_d1[25]}]
set_load -pin_load 1 [get_ports {fft_d1[24]}]
set_load -pin_load 1 [get_ports {fft_d1[23]}]
set_load -pin_load 1 [get_ports {fft_d1[22]}]
set_load -pin_load 1 [get_ports {fft_d1[21]}]
set_load -pin_load 1 [get_ports {fft_d1[20]}]
set_load -pin_load 1 [get_ports {fft_d1[19]}]
set_load -pin_load 1 [get_ports {fft_d1[18]}]
set_load -pin_load 1 [get_ports {fft_d1[17]}]
set_load -pin_load 1 [get_ports {fft_d1[16]}]
set_load -pin_load 1 [get_ports {fft_d1[15]}]
set_load -pin_load 1 [get_ports {fft_d1[14]}]
set_load -pin_load 1 [get_ports {fft_d1[13]}]
set_load -pin_load 1 [get_ports {fft_d1[12]}]
set_load -pin_load 1 [get_ports {fft_d1[11]}]
set_load -pin_load 1 [get_ports {fft_d1[10]}]
set_load -pin_load 1 [get_ports {fft_d1[9]}]
set_load -pin_load 1 [get_ports {fft_d1[8]}]
set_load -pin_load 1 [get_ports {fft_d1[7]}]
set_load -pin_load 1 [get_ports {fft_d1[6]}]
set_load -pin_load 1 [get_ports {fft_d1[5]}]
set_load -pin_load 1 [get_ports {fft_d1[4]}]
set_load -pin_load 1 [get_ports {fft_d1[3]}]
set_load -pin_load 1 [get_ports {fft_d1[2]}]
set_load -pin_load 1 [get_ports {fft_d1[1]}]
set_load -pin_load 1 [get_ports {fft_d1[0]}]
set_load -pin_load 1 [get_ports {fft_d2[31]}]
set_load -pin_load 1 [get_ports {fft_d2[30]}]
set_load -pin_load 1 [get_ports {fft_d2[29]}]
set_load -pin_load 1 [get_ports {fft_d2[28]}]
set_load -pin_load 1 [get_ports {fft_d2[27]}]
set_load -pin_load 1 [get_ports {fft_d2[26]}]
set_load -pin_load 1 [get_ports {fft_d2[25]}]
set_load -pin_load 1 [get_ports {fft_d2[24]}]
set_load -pin_load 1 [get_ports {fft_d2[23]}]
set_load -pin_load 1 [get_ports {fft_d2[22]}]
set_load -pin_load 1 [get_ports {fft_d2[21]}]
set_load -pin_load 1 [get_ports {fft_d2[20]}]
set_load -pin_load 1 [get_ports {fft_d2[19]}]
set_load -pin_load 1 [get_ports {fft_d2[18]}]
set_load -pin_load 1 [get_ports {fft_d2[17]}]
set_load -pin_load 1 [get_ports {fft_d2[16]}]
set_load -pin_load 1 [get_ports {fft_d2[15]}]
set_load -pin_load 1 [get_ports {fft_d2[14]}]
set_load -pin_load 1 [get_ports {fft_d2[13]}]
set_load -pin_load 1 [get_ports {fft_d2[12]}]
set_load -pin_load 1 [get_ports {fft_d2[11]}]
set_load -pin_load 1 [get_ports {fft_d2[10]}]
set_load -pin_load 1 [get_ports {fft_d2[9]}]
set_load -pin_load 1 [get_ports {fft_d2[8]}]
set_load -pin_load 1 [get_ports {fft_d2[7]}]
set_load -pin_load 1 [get_ports {fft_d2[6]}]
set_load -pin_load 1 [get_ports {fft_d2[5]}]
set_load -pin_load 1 [get_ports {fft_d2[4]}]
set_load -pin_load 1 [get_ports {fft_d2[3]}]
set_load -pin_load 1 [get_ports {fft_d2[2]}]
set_load -pin_load 1 [get_ports {fft_d2[1]}]
set_load -pin_load 1 [get_ports {fft_d2[0]}]
set_load -pin_load 1 [get_ports {fft_d3[31]}]
set_load -pin_load 1 [get_ports {fft_d3[30]}]
set_load -pin_load 1 [get_ports {fft_d3[29]}]
set_load -pin_load 1 [get_ports {fft_d3[28]}]
set_load -pin_load 1 [get_ports {fft_d3[27]}]
set_load -pin_load 1 [get_ports {fft_d3[26]}]
set_load -pin_load 1 [get_ports {fft_d3[25]}]
set_load -pin_load 1 [get_ports {fft_d3[24]}]
set_load -pin_load 1 [get_ports {fft_d3[23]}]
set_load -pin_load 1 [get_ports {fft_d3[22]}]
set_load -pin_load 1 [get_ports {fft_d3[21]}]
set_load -pin_load 1 [get_ports {fft_d3[20]}]
set_load -pin_load 1 [get_ports {fft_d3[19]}]
set_load -pin_load 1 [get_ports {fft_d3[18]}]
set_load -pin_load 1 [get_ports {fft_d3[17]}]
set_load -pin_load 1 [get_ports {fft_d3[16]}]
set_load -pin_load 1 [get_ports {fft_d3[15]}]
set_load -pin_load 1 [get_ports {fft_d3[14]}]
set_load -pin_load 1 [get_ports {fft_d3[13]}]
set_load -pin_load 1 [get_ports {fft_d3[12]}]
set_load -pin_load 1 [get_ports {fft_d3[11]}]
set_load -pin_load 1 [get_ports {fft_d3[10]}]
set_load -pin_load 1 [get_ports {fft_d3[9]}]
set_load -pin_load 1 [get_ports {fft_d3[8]}]
set_load -pin_load 1 [get_ports {fft_d3[7]}]
set_load -pin_load 1 [get_ports {fft_d3[6]}]
set_load -pin_load 1 [get_ports {fft_d3[5]}]
set_load -pin_load 1 [get_ports {fft_d3[4]}]
set_load -pin_load 1 [get_ports {fft_d3[3]}]
set_load -pin_load 1 [get_ports {fft_d3[2]}]
set_load -pin_load 1 [get_ports {fft_d3[1]}]
set_load -pin_load 1 [get_ports {fft_d3[0]}]
set_load -pin_load 1 [get_ports {fft_d4[31]}]
set_load -pin_load 1 [get_ports {fft_d4[30]}]
set_load -pin_load 1 [get_ports {fft_d4[29]}]
set_load -pin_load 1 [get_ports {fft_d4[28]}]
set_load -pin_load 1 [get_ports {fft_d4[27]}]
set_load -pin_load 1 [get_ports {fft_d4[26]}]
set_load -pin_load 1 [get_ports {fft_d4[25]}]
set_load -pin_load 1 [get_ports {fft_d4[24]}]
set_load -pin_load 1 [get_ports {fft_d4[23]}]
set_load -pin_load 1 [get_ports {fft_d4[22]}]
set_load -pin_load 1 [get_ports {fft_d4[21]}]
set_load -pin_load 1 [get_ports {fft_d4[20]}]
set_load -pin_load 1 [get_ports {fft_d4[19]}]
set_load -pin_load 1 [get_ports {fft_d4[18]}]
set_load -pin_load 1 [get_ports {fft_d4[17]}]
set_load -pin_load 1 [get_ports {fft_d4[16]}]
set_load -pin_load 1 [get_ports {fft_d4[15]}]
set_load -pin_load 1 [get_ports {fft_d4[14]}]
set_load -pin_load 1 [get_ports {fft_d4[13]}]
set_load -pin_load 1 [get_ports {fft_d4[12]}]
set_load -pin_load 1 [get_ports {fft_d4[11]}]
set_load -pin_load 1 [get_ports {fft_d4[10]}]
set_load -pin_load 1 [get_ports {fft_d4[9]}]
set_load -pin_load 1 [get_ports {fft_d4[8]}]
set_load -pin_load 1 [get_ports {fft_d4[7]}]
set_load -pin_load 1 [get_ports {fft_d4[6]}]
set_load -pin_load 1 [get_ports {fft_d4[5]}]
set_load -pin_load 1 [get_ports {fft_d4[4]}]
set_load -pin_load 1 [get_ports {fft_d4[3]}]
set_load -pin_load 1 [get_ports {fft_d4[2]}]
set_load -pin_load 1 [get_ports {fft_d4[1]}]
set_load -pin_load 1 [get_ports {fft_d4[0]}]
set_load -pin_load 1 [get_ports {fft_d5[31]}]
set_load -pin_load 1 [get_ports {fft_d5[30]}]
set_load -pin_load 1 [get_ports {fft_d5[29]}]
set_load -pin_load 1 [get_ports {fft_d5[28]}]
set_load -pin_load 1 [get_ports {fft_d5[27]}]
set_load -pin_load 1 [get_ports {fft_d5[26]}]
set_load -pin_load 1 [get_ports {fft_d5[25]}]
set_load -pin_load 1 [get_ports {fft_d5[24]}]
set_load -pin_load 1 [get_ports {fft_d5[23]}]
set_load -pin_load 1 [get_ports {fft_d5[22]}]
set_load -pin_load 1 [get_ports {fft_d5[21]}]
set_load -pin_load 1 [get_ports {fft_d5[20]}]
set_load -pin_load 1 [get_ports {fft_d5[19]}]
set_load -pin_load 1 [get_ports {fft_d5[18]}]
set_load -pin_load 1 [get_ports {fft_d5[17]}]
set_load -pin_load 1 [get_ports {fft_d5[16]}]
set_load -pin_load 1 [get_ports {fft_d5[15]}]
set_load -pin_load 1 [get_ports {fft_d5[14]}]
set_load -pin_load 1 [get_ports {fft_d5[13]}]
set_load -pin_load 1 [get_ports {fft_d5[12]}]
set_load -pin_load 1 [get_ports {fft_d5[11]}]
set_load -pin_load 1 [get_ports {fft_d5[10]}]
set_load -pin_load 1 [get_ports {fft_d5[9]}]
set_load -pin_load 1 [get_ports {fft_d5[8]}]
set_load -pin_load 1 [get_ports {fft_d5[7]}]
set_load -pin_load 1 [get_ports {fft_d5[6]}]
set_load -pin_load 1 [get_ports {fft_d5[5]}]
set_load -pin_load 1 [get_ports {fft_d5[4]}]
set_load -pin_load 1 [get_ports {fft_d5[3]}]
set_load -pin_load 1 [get_ports {fft_d5[2]}]
set_load -pin_load 1 [get_ports {fft_d5[1]}]
set_load -pin_load 1 [get_ports {fft_d5[0]}]
set_load -pin_load 1 [get_ports {fft_d6[31]}]
set_load -pin_load 1 [get_ports {fft_d6[30]}]
set_load -pin_load 1 [get_ports {fft_d6[29]}]
set_load -pin_load 1 [get_ports {fft_d6[28]}]
set_load -pin_load 1 [get_ports {fft_d6[27]}]
set_load -pin_load 1 [get_ports {fft_d6[26]}]
set_load -pin_load 1 [get_ports {fft_d6[25]}]
set_load -pin_load 1 [get_ports {fft_d6[24]}]
set_load -pin_load 1 [get_ports {fft_d6[23]}]
set_load -pin_load 1 [get_ports {fft_d6[22]}]
set_load -pin_load 1 [get_ports {fft_d6[21]}]
set_load -pin_load 1 [get_ports {fft_d6[20]}]
set_load -pin_load 1 [get_ports {fft_d6[19]}]
set_load -pin_load 1 [get_ports {fft_d6[18]}]
set_load -pin_load 1 [get_ports {fft_d6[17]}]
set_load -pin_load 1 [get_ports {fft_d6[16]}]
set_load -pin_load 1 [get_ports {fft_d6[15]}]
set_load -pin_load 1 [get_ports {fft_d6[14]}]
set_load -pin_load 1 [get_ports {fft_d6[13]}]
set_load -pin_load 1 [get_ports {fft_d6[12]}]
set_load -pin_load 1 [get_ports {fft_d6[11]}]
set_load -pin_load 1 [get_ports {fft_d6[10]}]
set_load -pin_load 1 [get_ports {fft_d6[9]}]
set_load -pin_load 1 [get_ports {fft_d6[8]}]
set_load -pin_load 1 [get_ports {fft_d6[7]}]
set_load -pin_load 1 [get_ports {fft_d6[6]}]
set_load -pin_load 1 [get_ports {fft_d6[5]}]
set_load -pin_load 1 [get_ports {fft_d6[4]}]
set_load -pin_load 1 [get_ports {fft_d6[3]}]
set_load -pin_load 1 [get_ports {fft_d6[2]}]
set_load -pin_load 1 [get_ports {fft_d6[1]}]
set_load -pin_load 1 [get_ports {fft_d6[0]}]
set_load -pin_load 1 [get_ports {fft_d7[31]}]
set_load -pin_load 1 [get_ports {fft_d7[30]}]
set_load -pin_load 1 [get_ports {fft_d7[29]}]
set_load -pin_load 1 [get_ports {fft_d7[28]}]
set_load -pin_load 1 [get_ports {fft_d7[27]}]
set_load -pin_load 1 [get_ports {fft_d7[26]}]
set_load -pin_load 1 [get_ports {fft_d7[25]}]
set_load -pin_load 1 [get_ports {fft_d7[24]}]
set_load -pin_load 1 [get_ports {fft_d7[23]}]
set_load -pin_load 1 [get_ports {fft_d7[22]}]
set_load -pin_load 1 [get_ports {fft_d7[21]}]
set_load -pin_load 1 [get_ports {fft_d7[20]}]
set_load -pin_load 1 [get_ports {fft_d7[19]}]
set_load -pin_load 1 [get_ports {fft_d7[18]}]
set_load -pin_load 1 [get_ports {fft_d7[17]}]
set_load -pin_load 1 [get_ports {fft_d7[16]}]
set_load -pin_load 1 [get_ports {fft_d7[15]}]
set_load -pin_load 1 [get_ports {fft_d7[14]}]
set_load -pin_load 1 [get_ports {fft_d7[13]}]
set_load -pin_load 1 [get_ports {fft_d7[12]}]
set_load -pin_load 1 [get_ports {fft_d7[11]}]
set_load -pin_load 1 [get_ports {fft_d7[10]}]
set_load -pin_load 1 [get_ports {fft_d7[9]}]
set_load -pin_load 1 [get_ports {fft_d7[8]}]
set_load -pin_load 1 [get_ports {fft_d7[7]}]
set_load -pin_load 1 [get_ports {fft_d7[6]}]
set_load -pin_load 1 [get_ports {fft_d7[5]}]
set_load -pin_load 1 [get_ports {fft_d7[4]}]
set_load -pin_load 1 [get_ports {fft_d7[3]}]
set_load -pin_load 1 [get_ports {fft_d7[2]}]
set_load -pin_load 1 [get_ports {fft_d7[1]}]
set_load -pin_load 1 [get_ports {fft_d7[0]}]
set_load -pin_load 1 [get_ports {fft_d8[31]}]
set_load -pin_load 1 [get_ports {fft_d8[30]}]
set_load -pin_load 1 [get_ports {fft_d8[29]}]
set_load -pin_load 1 [get_ports {fft_d8[28]}]
set_load -pin_load 1 [get_ports {fft_d8[27]}]
set_load -pin_load 1 [get_ports {fft_d8[26]}]
set_load -pin_load 1 [get_ports {fft_d8[25]}]
set_load -pin_load 1 [get_ports {fft_d8[24]}]
set_load -pin_load 1 [get_ports {fft_d8[23]}]
set_load -pin_load 1 [get_ports {fft_d8[22]}]
set_load -pin_load 1 [get_ports {fft_d8[21]}]
set_load -pin_load 1 [get_ports {fft_d8[20]}]
set_load -pin_load 1 [get_ports {fft_d8[19]}]
set_load -pin_load 1 [get_ports {fft_d8[18]}]
set_load -pin_load 1 [get_ports {fft_d8[17]}]
set_load -pin_load 1 [get_ports {fft_d8[16]}]
set_load -pin_load 1 [get_ports {fft_d8[15]}]
set_load -pin_load 1 [get_ports {fft_d8[14]}]
set_load -pin_load 1 [get_ports {fft_d8[13]}]
set_load -pin_load 1 [get_ports {fft_d8[12]}]
set_load -pin_load 1 [get_ports {fft_d8[11]}]
set_load -pin_load 1 [get_ports {fft_d8[10]}]
set_load -pin_load 1 [get_ports {fft_d8[9]}]
set_load -pin_load 1 [get_ports {fft_d8[8]}]
set_load -pin_load 1 [get_ports {fft_d8[7]}]
set_load -pin_load 1 [get_ports {fft_d8[6]}]
set_load -pin_load 1 [get_ports {fft_d8[5]}]
set_load -pin_load 1 [get_ports {fft_d8[4]}]
set_load -pin_load 1 [get_ports {fft_d8[3]}]
set_load -pin_load 1 [get_ports {fft_d8[2]}]
set_load -pin_load 1 [get_ports {fft_d8[1]}]
set_load -pin_load 1 [get_ports {fft_d8[0]}]
set_load -pin_load 1 [get_ports {fft_d9[31]}]
set_load -pin_load 1 [get_ports {fft_d9[30]}]
set_load -pin_load 1 [get_ports {fft_d9[29]}]
set_load -pin_load 1 [get_ports {fft_d9[28]}]
set_load -pin_load 1 [get_ports {fft_d9[27]}]
set_load -pin_load 1 [get_ports {fft_d9[26]}]
set_load -pin_load 1 [get_ports {fft_d9[25]}]
set_load -pin_load 1 [get_ports {fft_d9[24]}]
set_load -pin_load 1 [get_ports {fft_d9[23]}]
set_load -pin_load 1 [get_ports {fft_d9[22]}]
set_load -pin_load 1 [get_ports {fft_d9[21]}]
set_load -pin_load 1 [get_ports {fft_d9[20]}]
set_load -pin_load 1 [get_ports {fft_d9[19]}]
set_load -pin_load 1 [get_ports {fft_d9[18]}]
set_load -pin_load 1 [get_ports {fft_d9[17]}]
set_load -pin_load 1 [get_ports {fft_d9[16]}]
set_load -pin_load 1 [get_ports {fft_d9[15]}]
set_load -pin_load 1 [get_ports {fft_d9[14]}]
set_load -pin_load 1 [get_ports {fft_d9[13]}]
set_load -pin_load 1 [get_ports {fft_d9[12]}]
set_load -pin_load 1 [get_ports {fft_d9[11]}]
set_load -pin_load 1 [get_ports {fft_d9[10]}]
set_load -pin_load 1 [get_ports {fft_d9[9]}]
set_load -pin_load 1 [get_ports {fft_d9[8]}]
set_load -pin_load 1 [get_ports {fft_d9[7]}]
set_load -pin_load 1 [get_ports {fft_d9[6]}]
set_load -pin_load 1 [get_ports {fft_d9[5]}]
set_load -pin_load 1 [get_ports {fft_d9[4]}]
set_load -pin_load 1 [get_ports {fft_d9[3]}]
set_load -pin_load 1 [get_ports {fft_d9[2]}]
set_load -pin_load 1 [get_ports {fft_d9[1]}]
set_load -pin_load 1 [get_ports {fft_d9[0]}]
set_load -pin_load 1 [get_ports {fft_d10[31]}]
set_load -pin_load 1 [get_ports {fft_d10[30]}]
set_load -pin_load 1 [get_ports {fft_d10[29]}]
set_load -pin_load 1 [get_ports {fft_d10[28]}]
set_load -pin_load 1 [get_ports {fft_d10[27]}]
set_load -pin_load 1 [get_ports {fft_d10[26]}]
set_load -pin_load 1 [get_ports {fft_d10[25]}]
set_load -pin_load 1 [get_ports {fft_d10[24]}]
set_load -pin_load 1 [get_ports {fft_d10[23]}]
set_load -pin_load 1 [get_ports {fft_d10[22]}]
set_load -pin_load 1 [get_ports {fft_d10[21]}]
set_load -pin_load 1 [get_ports {fft_d10[20]}]
set_load -pin_load 1 [get_ports {fft_d10[19]}]
set_load -pin_load 1 [get_ports {fft_d10[18]}]
set_load -pin_load 1 [get_ports {fft_d10[17]}]
set_load -pin_load 1 [get_ports {fft_d10[16]}]
set_load -pin_load 1 [get_ports {fft_d10[15]}]
set_load -pin_load 1 [get_ports {fft_d10[14]}]
set_load -pin_load 1 [get_ports {fft_d10[13]}]
set_load -pin_load 1 [get_ports {fft_d10[12]}]
set_load -pin_load 1 [get_ports {fft_d10[11]}]
set_load -pin_load 1 [get_ports {fft_d10[10]}]
set_load -pin_load 1 [get_ports {fft_d10[9]}]
set_load -pin_load 1 [get_ports {fft_d10[8]}]
set_load -pin_load 1 [get_ports {fft_d10[7]}]
set_load -pin_load 1 [get_ports {fft_d10[6]}]
set_load -pin_load 1 [get_ports {fft_d10[5]}]
set_load -pin_load 1 [get_ports {fft_d10[4]}]
set_load -pin_load 1 [get_ports {fft_d10[3]}]
set_load -pin_load 1 [get_ports {fft_d10[2]}]
set_load -pin_load 1 [get_ports {fft_d10[1]}]
set_load -pin_load 1 [get_ports {fft_d10[0]}]
set_load -pin_load 1 [get_ports {fft_d11[31]}]
set_load -pin_load 1 [get_ports {fft_d11[30]}]
set_load -pin_load 1 [get_ports {fft_d11[29]}]
set_load -pin_load 1 [get_ports {fft_d11[28]}]
set_load -pin_load 1 [get_ports {fft_d11[27]}]
set_load -pin_load 1 [get_ports {fft_d11[26]}]
set_load -pin_load 1 [get_ports {fft_d11[25]}]
set_load -pin_load 1 [get_ports {fft_d11[24]}]
set_load -pin_load 1 [get_ports {fft_d11[23]}]
set_load -pin_load 1 [get_ports {fft_d11[22]}]
set_load -pin_load 1 [get_ports {fft_d11[21]}]
set_load -pin_load 1 [get_ports {fft_d11[20]}]
set_load -pin_load 1 [get_ports {fft_d11[19]}]
set_load -pin_load 1 [get_ports {fft_d11[18]}]
set_load -pin_load 1 [get_ports {fft_d11[17]}]
set_load -pin_load 1 [get_ports {fft_d11[16]}]
set_load -pin_load 1 [get_ports {fft_d11[15]}]
set_load -pin_load 1 [get_ports {fft_d11[14]}]
set_load -pin_load 1 [get_ports {fft_d11[13]}]
set_load -pin_load 1 [get_ports {fft_d11[12]}]
set_load -pin_load 1 [get_ports {fft_d11[11]}]
set_load -pin_load 1 [get_ports {fft_d11[10]}]
set_load -pin_load 1 [get_ports {fft_d11[9]}]
set_load -pin_load 1 [get_ports {fft_d11[8]}]
set_load -pin_load 1 [get_ports {fft_d11[7]}]
set_load -pin_load 1 [get_ports {fft_d11[6]}]
set_load -pin_load 1 [get_ports {fft_d11[5]}]
set_load -pin_load 1 [get_ports {fft_d11[4]}]
set_load -pin_load 1 [get_ports {fft_d11[3]}]
set_load -pin_load 1 [get_ports {fft_d11[2]}]
set_load -pin_load 1 [get_ports {fft_d11[1]}]
set_load -pin_load 1 [get_ports {fft_d11[0]}]
set_load -pin_load 1 [get_ports {fft_d12[31]}]
set_load -pin_load 1 [get_ports {fft_d12[30]}]
set_load -pin_load 1 [get_ports {fft_d12[29]}]
set_load -pin_load 1 [get_ports {fft_d12[28]}]
set_load -pin_load 1 [get_ports {fft_d12[27]}]
set_load -pin_load 1 [get_ports {fft_d12[26]}]
set_load -pin_load 1 [get_ports {fft_d12[25]}]
set_load -pin_load 1 [get_ports {fft_d12[24]}]
set_load -pin_load 1 [get_ports {fft_d12[23]}]
set_load -pin_load 1 [get_ports {fft_d12[22]}]
set_load -pin_load 1 [get_ports {fft_d12[21]}]
set_load -pin_load 1 [get_ports {fft_d12[20]}]
set_load -pin_load 1 [get_ports {fft_d12[19]}]
set_load -pin_load 1 [get_ports {fft_d12[18]}]
set_load -pin_load 1 [get_ports {fft_d12[17]}]
set_load -pin_load 1 [get_ports {fft_d12[16]}]
set_load -pin_load 1 [get_ports {fft_d12[15]}]
set_load -pin_load 1 [get_ports {fft_d12[14]}]
set_load -pin_load 1 [get_ports {fft_d12[13]}]
set_load -pin_load 1 [get_ports {fft_d12[12]}]
set_load -pin_load 1 [get_ports {fft_d12[11]}]
set_load -pin_load 1 [get_ports {fft_d12[10]}]
set_load -pin_load 1 [get_ports {fft_d12[9]}]
set_load -pin_load 1 [get_ports {fft_d12[8]}]
set_load -pin_load 1 [get_ports {fft_d12[7]}]
set_load -pin_load 1 [get_ports {fft_d12[6]}]
set_load -pin_load 1 [get_ports {fft_d12[5]}]
set_load -pin_load 1 [get_ports {fft_d12[4]}]
set_load -pin_load 1 [get_ports {fft_d12[3]}]
set_load -pin_load 1 [get_ports {fft_d12[2]}]
set_load -pin_load 1 [get_ports {fft_d12[1]}]
set_load -pin_load 1 [get_ports {fft_d12[0]}]
set_load -pin_load 1 [get_ports {fft_d13[31]}]
set_load -pin_load 1 [get_ports {fft_d13[30]}]
set_load -pin_load 1 [get_ports {fft_d13[29]}]
set_load -pin_load 1 [get_ports {fft_d13[28]}]
set_load -pin_load 1 [get_ports {fft_d13[27]}]
set_load -pin_load 1 [get_ports {fft_d13[26]}]
set_load -pin_load 1 [get_ports {fft_d13[25]}]
set_load -pin_load 1 [get_ports {fft_d13[24]}]
set_load -pin_load 1 [get_ports {fft_d13[23]}]
set_load -pin_load 1 [get_ports {fft_d13[22]}]
set_load -pin_load 1 [get_ports {fft_d13[21]}]
set_load -pin_load 1 [get_ports {fft_d13[20]}]
set_load -pin_load 1 [get_ports {fft_d13[19]}]
set_load -pin_load 1 [get_ports {fft_d13[18]}]
set_load -pin_load 1 [get_ports {fft_d13[17]}]
set_load -pin_load 1 [get_ports {fft_d13[16]}]
set_load -pin_load 1 [get_ports {fft_d13[15]}]
set_load -pin_load 1 [get_ports {fft_d13[14]}]
set_load -pin_load 1 [get_ports {fft_d13[13]}]
set_load -pin_load 1 [get_ports {fft_d13[12]}]
set_load -pin_load 1 [get_ports {fft_d13[11]}]
set_load -pin_load 1 [get_ports {fft_d13[10]}]
set_load -pin_load 1 [get_ports {fft_d13[9]}]
set_load -pin_load 1 [get_ports {fft_d13[8]}]
set_load -pin_load 1 [get_ports {fft_d13[7]}]
set_load -pin_load 1 [get_ports {fft_d13[6]}]
set_load -pin_load 1 [get_ports {fft_d13[5]}]
set_load -pin_load 1 [get_ports {fft_d13[4]}]
set_load -pin_load 1 [get_ports {fft_d13[3]}]
set_load -pin_load 1 [get_ports {fft_d13[2]}]
set_load -pin_load 1 [get_ports {fft_d13[1]}]
set_load -pin_load 1 [get_ports {fft_d13[0]}]
set_load -pin_load 1 [get_ports {fft_d14[31]}]
set_load -pin_load 1 [get_ports {fft_d14[30]}]
set_load -pin_load 1 [get_ports {fft_d14[29]}]
set_load -pin_load 1 [get_ports {fft_d14[28]}]
set_load -pin_load 1 [get_ports {fft_d14[27]}]
set_load -pin_load 1 [get_ports {fft_d14[26]}]
set_load -pin_load 1 [get_ports {fft_d14[25]}]
set_load -pin_load 1 [get_ports {fft_d14[24]}]
set_load -pin_load 1 [get_ports {fft_d14[23]}]
set_load -pin_load 1 [get_ports {fft_d14[22]}]
set_load -pin_load 1 [get_ports {fft_d14[21]}]
set_load -pin_load 1 [get_ports {fft_d14[20]}]
set_load -pin_load 1 [get_ports {fft_d14[19]}]
set_load -pin_load 1 [get_ports {fft_d14[18]}]
set_load -pin_load 1 [get_ports {fft_d14[17]}]
set_load -pin_load 1 [get_ports {fft_d14[16]}]
set_load -pin_load 1 [get_ports {fft_d14[15]}]
set_load -pin_load 1 [get_ports {fft_d14[14]}]
set_load -pin_load 1 [get_ports {fft_d14[13]}]
set_load -pin_load 1 [get_ports {fft_d14[12]}]
set_load -pin_load 1 [get_ports {fft_d14[11]}]
set_load -pin_load 1 [get_ports {fft_d14[10]}]
set_load -pin_load 1 [get_ports {fft_d14[9]}]
set_load -pin_load 1 [get_ports {fft_d14[8]}]
set_load -pin_load 1 [get_ports {fft_d14[7]}]
set_load -pin_load 1 [get_ports {fft_d14[6]}]
set_load -pin_load 1 [get_ports {fft_d14[5]}]
set_load -pin_load 1 [get_ports {fft_d14[4]}]
set_load -pin_load 1 [get_ports {fft_d14[3]}]
set_load -pin_load 1 [get_ports {fft_d14[2]}]
set_load -pin_load 1 [get_ports {fft_d14[1]}]
set_load -pin_load 1 [get_ports {fft_d14[0]}]
set_load -pin_load 1 [get_ports {fft_d15[31]}]
set_load -pin_load 1 [get_ports {fft_d15[30]}]
set_load -pin_load 1 [get_ports {fft_d15[29]}]
set_load -pin_load 1 [get_ports {fft_d15[28]}]
set_load -pin_load 1 [get_ports {fft_d15[27]}]
set_load -pin_load 1 [get_ports {fft_d15[26]}]
set_load -pin_load 1 [get_ports {fft_d15[25]}]
set_load -pin_load 1 [get_ports {fft_d15[24]}]
set_load -pin_load 1 [get_ports {fft_d15[23]}]
set_load -pin_load 1 [get_ports {fft_d15[22]}]
set_load -pin_load 1 [get_ports {fft_d15[21]}]
set_load -pin_load 1 [get_ports {fft_d15[20]}]
set_load -pin_load 1 [get_ports {fft_d15[19]}]
set_load -pin_load 1 [get_ports {fft_d15[18]}]
set_load -pin_load 1 [get_ports {fft_d15[17]}]
set_load -pin_load 1 [get_ports {fft_d15[16]}]
set_load -pin_load 1 [get_ports {fft_d15[15]}]
set_load -pin_load 1 [get_ports {fft_d15[14]}]
set_load -pin_load 1 [get_ports {fft_d15[13]}]
set_load -pin_load 1 [get_ports {fft_d15[12]}]
set_load -pin_load 1 [get_ports {fft_d15[11]}]
set_load -pin_load 1 [get_ports {fft_d15[10]}]
set_load -pin_load 1 [get_ports {fft_d15[9]}]
set_load -pin_load 1 [get_ports {fft_d15[8]}]
set_load -pin_load 1 [get_ports {fft_d15[7]}]
set_load -pin_load 1 [get_ports {fft_d15[6]}]
set_load -pin_load 1 [get_ports {fft_d15[5]}]
set_load -pin_load 1 [get_ports {fft_d15[4]}]
set_load -pin_load 1 [get_ports {fft_d15[3]}]
set_load -pin_load 1 [get_ports {fft_d15[2]}]
set_load -pin_load 1 [get_ports {fft_d15[1]}]
set_load -pin_load 1 [get_ports {fft_d15[0]}]
set_load -pin_load 1 [get_ports {fft_d0[31]}]
set_load -pin_load 1 [get_ports {fft_d0[30]}]
set_load -pin_load 1 [get_ports {fft_d0[29]}]
set_load -pin_load 1 [get_ports {fft_d0[28]}]
set_load -pin_load 1 [get_ports {fft_d0[27]}]
set_load -pin_load 1 [get_ports {fft_d0[26]}]
set_load -pin_load 1 [get_ports {fft_d0[25]}]
set_load -pin_load 1 [get_ports {fft_d0[24]}]
set_load -pin_load 1 [get_ports {fft_d0[23]}]
set_load -pin_load 1 [get_ports {fft_d0[22]}]
set_load -pin_load 1 [get_ports {fft_d0[21]}]
set_load -pin_load 1 [get_ports {fft_d0[20]}]
set_load -pin_load 1 [get_ports {fft_d0[19]}]
set_load -pin_load 1 [get_ports {fft_d0[18]}]
set_load -pin_load 1 [get_ports {fft_d0[17]}]
set_load -pin_load 1 [get_ports {fft_d0[16]}]
set_load -pin_load 1 [get_ports {fft_d0[15]}]
set_load -pin_load 1 [get_ports {fft_d0[14]}]
set_load -pin_load 1 [get_ports {fft_d0[13]}]
set_load -pin_load 1 [get_ports {fft_d0[12]}]
set_load -pin_load 1 [get_ports {fft_d0[11]}]
set_load -pin_load 1 [get_ports {fft_d0[10]}]
set_load -pin_load 1 [get_ports {fft_d0[9]}]
set_load -pin_load 1 [get_ports {fft_d0[8]}]
set_load -pin_load 1 [get_ports {fft_d0[7]}]
set_load -pin_load 1 [get_ports {fft_d0[6]}]
set_load -pin_load 1 [get_ports {fft_d0[5]}]
set_load -pin_load 1 [get_ports {fft_d0[4]}]
set_load -pin_load 1 [get_ports {fft_d0[3]}]
set_load -pin_load 1 [get_ports {fft_d0[2]}]
set_load -pin_load 1 [get_ports {fft_d0[1]}]
set_load -pin_load 1 [get_ports {fft_d0[0]}]
set_load -pin_load 1 [get_ports done]
set_load -pin_load 1 [get_ports {freq[3]}]
set_load -pin_load 1 [get_ports {freq[2]}]
set_load -pin_load 1 [get_ports {freq[1]}]
set_load -pin_load 1 [get_ports {freq[0]}]
set_max_fanout 20 [get_ports clk]
set_max_fanout 20 [get_ports rst]
set_max_fanout 20 [get_ports data_valid]
set_max_fanout 20 [get_ports {data[15]}]
set_max_fanout 20 [get_ports {data[14]}]
set_max_fanout 20 [get_ports {data[13]}]
set_max_fanout 20 [get_ports {data[12]}]
set_max_fanout 20 [get_ports {data[11]}]
set_max_fanout 20 [get_ports {data[10]}]
set_max_fanout 20 [get_ports {data[9]}]
set_max_fanout 20 [get_ports {data[8]}]
set_max_fanout 20 [get_ports {data[7]}]
set_max_fanout 20 [get_ports {data[6]}]
set_max_fanout 20 [get_ports {data[5]}]
set_max_fanout 20 [get_ports {data[4]}]
set_max_fanout 20 [get_ports {data[3]}]
set_max_fanout 20 [get_ports {data[2]}]
set_max_fanout 20 [get_ports {data[1]}]
set_max_fanout 20 [get_ports {data[0]}]
create_clock [get_ports clk]  -period 12  -waveform {0 6}
set_clock_uncertainty 1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst]
set_input_delay -clock clk  -max 6  [get_ports data_valid]
set_input_delay -clock clk  -min 0  [get_ports data_valid]
set_input_delay -clock clk  -max 6  [get_ports {data[15]}]
set_input_delay -clock clk  -min 0  [get_ports {data[15]}]
set_input_delay -clock clk  -max 6  [get_ports {data[14]}]
set_input_delay -clock clk  -min 0  [get_ports {data[14]}]
set_input_delay -clock clk  -max 6  [get_ports {data[13]}]
set_input_delay -clock clk  -min 0  [get_ports {data[13]}]
set_input_delay -clock clk  -max 6  [get_ports {data[12]}]
set_input_delay -clock clk  -min 0  [get_ports {data[12]}]
set_input_delay -clock clk  -max 6  [get_ports {data[11]}]
set_input_delay -clock clk  -min 0  [get_ports {data[11]}]
set_input_delay -clock clk  -max 6  [get_ports {data[10]}]
set_input_delay -clock clk  -min 0  [get_ports {data[10]}]
set_input_delay -clock clk  -max 6  [get_ports {data[9]}]
set_input_delay -clock clk  -min 0  [get_ports {data[9]}]
set_input_delay -clock clk  -max 6  [get_ports {data[8]}]
set_input_delay -clock clk  -min 0  [get_ports {data[8]}]
set_input_delay -clock clk  -max 6  [get_ports {data[7]}]
set_input_delay -clock clk  -min 0  [get_ports {data[7]}]
set_input_delay -clock clk  -max 6  [get_ports {data[6]}]
set_input_delay -clock clk  -min 0  [get_ports {data[6]}]
set_input_delay -clock clk  -max 6  [get_ports {data[5]}]
set_input_delay -clock clk  -min 0  [get_ports {data[5]}]
set_input_delay -clock clk  -max 6  [get_ports {data[4]}]
set_input_delay -clock clk  -min 0  [get_ports {data[4]}]
set_input_delay -clock clk  -max 6  [get_ports {data[3]}]
set_input_delay -clock clk  -min 0  [get_ports {data[3]}]
set_input_delay -clock clk  -max 6  [get_ports {data[2]}]
set_input_delay -clock clk  -min 0  [get_ports {data[2]}]
set_input_delay -clock clk  -max 6  [get_ports {data[1]}]
set_input_delay -clock clk  -min 0  [get_ports {data[1]}]
set_input_delay -clock clk  -max 6  [get_ports {data[0]}]
set_input_delay -clock clk  -min 0  [get_ports {data[0]}]
set_output_delay -clock clk  -max 6  [get_ports fir_valid]
set_output_delay -clock clk  -min 0  [get_ports fir_valid]
set_output_delay -clock clk  -max 6  [get_ports fft_valid]
set_output_delay -clock clk  -min 0  [get_ports fft_valid]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fir_d[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fir_d[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d1[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d1[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d2[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d2[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d3[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d3[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d4[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d4[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d5[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d5[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d6[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d6[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d7[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d7[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d8[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d8[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d9[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d9[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d10[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d10[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d11[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d11[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d12[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d12[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d13[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d13[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d14[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d14[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d15[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d15[0]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[31]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[31]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[30]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[30]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[29]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[29]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[28]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[28]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[27]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[27]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[26]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[26]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[25]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[25]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[24]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[24]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[23]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[23]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[22]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[22]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[21]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[21]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[20]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[20]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[19]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[19]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[18]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[18]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[17]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[17]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[16]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[16]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[15]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[15]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[14]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[14]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[13]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[13]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[12]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[12]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[11]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[11]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[10]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[10]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[9]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[9]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[8]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[8]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[7]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[7]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[6]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[6]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[5]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[5]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[4]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[4]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[3]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[3]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[2]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[2]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[1]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[1]}]
set_output_delay -clock clk  -max 6  [get_ports {fft_d0[0]}]
set_output_delay -clock clk  -min 0  [get_ports {fft_d0[0]}]
set_output_delay -clock clk  -max 6  [get_ports done]
set_output_delay -clock clk  -min 0  [get_ports done]
set_output_delay -clock clk  -max 6  [get_ports {freq[3]}]
set_output_delay -clock clk  -min 0  [get_ports {freq[3]}]
set_output_delay -clock clk  -max 6  [get_ports {freq[2]}]
set_output_delay -clock clk  -min 0  [get_ports {freq[2]}]
set_output_delay -clock clk  -max 6  [get_ports {freq[1]}]
set_output_delay -clock clk  -min 0  [get_ports {freq[1]}]
set_output_delay -clock clk  -max 6  [get_ports {freq[0]}]
set_output_delay -clock clk  -min 0  [get_ports {freq[0]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports rst]
set_drive 1  [get_ports data_valid]
set_drive 1  [get_ports {data[15]}]
set_drive 1  [get_ports {data[14]}]
set_drive 1  [get_ports {data[13]}]
set_drive 1  [get_ports {data[12]}]
set_drive 1  [get_ports {data[11]}]
set_drive 1  [get_ports {data[10]}]
set_drive 1  [get_ports {data[9]}]
set_drive 1  [get_ports {data[8]}]
set_drive 1  [get_ports {data[7]}]
set_drive 1  [get_ports {data[6]}]
set_drive 1  [get_ports {data[5]}]
set_drive 1  [get_ports {data[4]}]
set_drive 1  [get_ports {data[3]}]
set_drive 1  [get_ports {data[2]}]
set_drive 1  [get_ports {data[1]}]
set_drive 1  [get_ports {data[0]}]
