###################################################################

# Created by write_sdc on Mon Jan 27 23:53:48 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max slow -max_library slow\
                         -min fast -min_library fast
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 0.1 [get_ports CNT_valid]
set_load -pin_load 0.1 [get_ports {CNT1[7]}]
set_load -pin_load 0.1 [get_ports {CNT1[6]}]
set_load -pin_load 0.1 [get_ports {CNT1[5]}]
set_load -pin_load 0.1 [get_ports {CNT1[4]}]
set_load -pin_load 0.1 [get_ports {CNT1[3]}]
set_load -pin_load 0.1 [get_ports {CNT1[2]}]
set_load -pin_load 0.1 [get_ports {CNT1[1]}]
set_load -pin_load 0.1 [get_ports {CNT1[0]}]
set_load -pin_load 0.1 [get_ports {CNT2[7]}]
set_load -pin_load 0.1 [get_ports {CNT2[6]}]
set_load -pin_load 0.1 [get_ports {CNT2[5]}]
set_load -pin_load 0.1 [get_ports {CNT2[4]}]
set_load -pin_load 0.1 [get_ports {CNT2[3]}]
set_load -pin_load 0.1 [get_ports {CNT2[2]}]
set_load -pin_load 0.1 [get_ports {CNT2[1]}]
set_load -pin_load 0.1 [get_ports {CNT2[0]}]
set_load -pin_load 0.1 [get_ports {CNT3[7]}]
set_load -pin_load 0.1 [get_ports {CNT3[6]}]
set_load -pin_load 0.1 [get_ports {CNT3[5]}]
set_load -pin_load 0.1 [get_ports {CNT3[4]}]
set_load -pin_load 0.1 [get_ports {CNT3[3]}]
set_load -pin_load 0.1 [get_ports {CNT3[2]}]
set_load -pin_load 0.1 [get_ports {CNT3[1]}]
set_load -pin_load 0.1 [get_ports {CNT3[0]}]
set_load -pin_load 0.1 [get_ports {CNT4[7]}]
set_load -pin_load 0.1 [get_ports {CNT4[6]}]
set_load -pin_load 0.1 [get_ports {CNT4[5]}]
set_load -pin_load 0.1 [get_ports {CNT4[4]}]
set_load -pin_load 0.1 [get_ports {CNT4[3]}]
set_load -pin_load 0.1 [get_ports {CNT4[2]}]
set_load -pin_load 0.1 [get_ports {CNT4[1]}]
set_load -pin_load 0.1 [get_ports {CNT4[0]}]
set_load -pin_load 0.1 [get_ports {CNT5[7]}]
set_load -pin_load 0.1 [get_ports {CNT5[6]}]
set_load -pin_load 0.1 [get_ports {CNT5[5]}]
set_load -pin_load 0.1 [get_ports {CNT5[4]}]
set_load -pin_load 0.1 [get_ports {CNT5[3]}]
set_load -pin_load 0.1 [get_ports {CNT5[2]}]
set_load -pin_load 0.1 [get_ports {CNT5[1]}]
set_load -pin_load 0.1 [get_ports {CNT5[0]}]
set_load -pin_load 0.1 [get_ports {CNT6[7]}]
set_load -pin_load 0.1 [get_ports {CNT6[6]}]
set_load -pin_load 0.1 [get_ports {CNT6[5]}]
set_load -pin_load 0.1 [get_ports {CNT6[4]}]
set_load -pin_load 0.1 [get_ports {CNT6[3]}]
set_load -pin_load 0.1 [get_ports {CNT6[2]}]
set_load -pin_load 0.1 [get_ports {CNT6[1]}]
set_load -pin_load 0.1 [get_ports {CNT6[0]}]
set_load -pin_load 0.1 [get_ports code_valid]
set_load -pin_load 0.1 [get_ports {HC1[7]}]
set_load -pin_load 0.1 [get_ports {HC1[6]}]
set_load -pin_load 0.1 [get_ports {HC1[5]}]
set_load -pin_load 0.1 [get_ports {HC1[4]}]
set_load -pin_load 0.1 [get_ports {HC1[3]}]
set_load -pin_load 0.1 [get_ports {HC1[2]}]
set_load -pin_load 0.1 [get_ports {HC1[1]}]
set_load -pin_load 0.1 [get_ports {HC1[0]}]
set_load -pin_load 0.1 [get_ports {HC2[7]}]
set_load -pin_load 0.1 [get_ports {HC2[6]}]
set_load -pin_load 0.1 [get_ports {HC2[5]}]
set_load -pin_load 0.1 [get_ports {HC2[4]}]
set_load -pin_load 0.1 [get_ports {HC2[3]}]
set_load -pin_load 0.1 [get_ports {HC2[2]}]
set_load -pin_load 0.1 [get_ports {HC2[1]}]
set_load -pin_load 0.1 [get_ports {HC2[0]}]
set_load -pin_load 0.1 [get_ports {HC3[7]}]
set_load -pin_load 0.1 [get_ports {HC3[6]}]
set_load -pin_load 0.1 [get_ports {HC3[5]}]
set_load -pin_load 0.1 [get_ports {HC3[4]}]
set_load -pin_load 0.1 [get_ports {HC3[3]}]
set_load -pin_load 0.1 [get_ports {HC3[2]}]
set_load -pin_load 0.1 [get_ports {HC3[1]}]
set_load -pin_load 0.1 [get_ports {HC3[0]}]
set_load -pin_load 0.1 [get_ports {HC4[7]}]
set_load -pin_load 0.1 [get_ports {HC4[6]}]
set_load -pin_load 0.1 [get_ports {HC4[5]}]
set_load -pin_load 0.1 [get_ports {HC4[4]}]
set_load -pin_load 0.1 [get_ports {HC4[3]}]
set_load -pin_load 0.1 [get_ports {HC4[2]}]
set_load -pin_load 0.1 [get_ports {HC4[1]}]
set_load -pin_load 0.1 [get_ports {HC4[0]}]
set_load -pin_load 0.1 [get_ports {HC5[7]}]
set_load -pin_load 0.1 [get_ports {HC5[6]}]
set_load -pin_load 0.1 [get_ports {HC5[5]}]
set_load -pin_load 0.1 [get_ports {HC5[4]}]
set_load -pin_load 0.1 [get_ports {HC5[3]}]
set_load -pin_load 0.1 [get_ports {HC5[2]}]
set_load -pin_load 0.1 [get_ports {HC5[1]}]
set_load -pin_load 0.1 [get_ports {HC5[0]}]
set_load -pin_load 0.1 [get_ports {HC6[7]}]
set_load -pin_load 0.1 [get_ports {HC6[6]}]
set_load -pin_load 0.1 [get_ports {HC6[5]}]
set_load -pin_load 0.1 [get_ports {HC6[4]}]
set_load -pin_load 0.1 [get_ports {HC6[3]}]
set_load -pin_load 0.1 [get_ports {HC6[2]}]
set_load -pin_load 0.1 [get_ports {HC6[1]}]
set_load -pin_load 0.1 [get_ports {HC6[0]}]
set_load -pin_load 0.1 [get_ports {M1[7]}]
set_load -pin_load 0.1 [get_ports {M1[6]}]
set_load -pin_load 0.1 [get_ports {M1[5]}]
set_load -pin_load 0.1 [get_ports {M1[4]}]
set_load -pin_load 0.1 [get_ports {M1[3]}]
set_load -pin_load 0.1 [get_ports {M1[2]}]
set_load -pin_load 0.1 [get_ports {M1[1]}]
set_load -pin_load 0.1 [get_ports {M1[0]}]
set_load -pin_load 0.1 [get_ports {M2[7]}]
set_load -pin_load 0.1 [get_ports {M2[6]}]
set_load -pin_load 0.1 [get_ports {M2[5]}]
set_load -pin_load 0.1 [get_ports {M2[4]}]
set_load -pin_load 0.1 [get_ports {M2[3]}]
set_load -pin_load 0.1 [get_ports {M2[2]}]
set_load -pin_load 0.1 [get_ports {M2[1]}]
set_load -pin_load 0.1 [get_ports {M2[0]}]
set_load -pin_load 0.1 [get_ports {M3[7]}]
set_load -pin_load 0.1 [get_ports {M3[6]}]
set_load -pin_load 0.1 [get_ports {M3[5]}]
set_load -pin_load 0.1 [get_ports {M3[4]}]
set_load -pin_load 0.1 [get_ports {M3[3]}]
set_load -pin_load 0.1 [get_ports {M3[2]}]
set_load -pin_load 0.1 [get_ports {M3[1]}]
set_load -pin_load 0.1 [get_ports {M3[0]}]
set_load -pin_load 0.1 [get_ports {M4[7]}]
set_load -pin_load 0.1 [get_ports {M4[6]}]
set_load -pin_load 0.1 [get_ports {M4[5]}]
set_load -pin_load 0.1 [get_ports {M4[4]}]
set_load -pin_load 0.1 [get_ports {M4[3]}]
set_load -pin_load 0.1 [get_ports {M4[2]}]
set_load -pin_load 0.1 [get_ports {M4[1]}]
set_load -pin_load 0.1 [get_ports {M4[0]}]
set_load -pin_load 0.1 [get_ports {M5[7]}]
set_load -pin_load 0.1 [get_ports {M5[6]}]
set_load -pin_load 0.1 [get_ports {M5[5]}]
set_load -pin_load 0.1 [get_ports {M5[4]}]
set_load -pin_load 0.1 [get_ports {M5[3]}]
set_load -pin_load 0.1 [get_ports {M5[2]}]
set_load -pin_load 0.1 [get_ports {M5[1]}]
set_load -pin_load 0.1 [get_ports {M5[0]}]
set_load -pin_load 0.1 [get_ports {M6[7]}]
set_load -pin_load 0.1 [get_ports {M6[6]}]
set_load -pin_load 0.1 [get_ports {M6[5]}]
set_load -pin_load 0.1 [get_ports {M6[4]}]
set_load -pin_load 0.1 [get_ports {M6[3]}]
set_load -pin_load 0.1 [get_ports {M6[2]}]
set_load -pin_load 0.1 [get_ports {M6[1]}]
set_load -pin_load 0.1 [get_ports {M6[0]}]
set_max_fanout 20 [get_ports clk]
set_max_fanout 20 [get_ports reset]
set_max_fanout 20 [get_ports gray_valid]
set_max_fanout 20 [get_ports {gray_data[7]}]
set_max_fanout 20 [get_ports {gray_data[6]}]
set_max_fanout 20 [get_ports {gray_data[5]}]
set_max_fanout 20 [get_ports {gray_data[4]}]
set_max_fanout 20 [get_ports {gray_data[3]}]
set_max_fanout 20 [get_ports {gray_data[2]}]
set_max_fanout 20 [get_ports {gray_data[1]}]
set_max_fanout 20 [get_ports {gray_data[0]}]
create_clock [get_ports clk]  -period 7  -waveform {0 3.5}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty 0.1  [get_clocks clk]
set_input_delay -clock clk  3.5  [get_ports reset]
set_input_delay -clock clk  3.5  [get_ports gray_valid]
set_input_delay -clock clk  3.5  [get_ports {gray_data[7]}]
set_input_delay -clock clk  3.5  [get_ports {gray_data[6]}]
set_input_delay -clock clk  3.5  [get_ports {gray_data[5]}]
set_input_delay -clock clk  3.5  [get_ports {gray_data[4]}]
set_input_delay -clock clk  3.5  [get_ports {gray_data[3]}]
set_input_delay -clock clk  3.5  [get_ports {gray_data[2]}]
set_input_delay -clock clk  3.5  [get_ports {gray_data[1]}]
set_input_delay -clock clk  3.5  [get_ports {gray_data[0]}]
set_output_delay -clock clk  0.5  [get_ports CNT_valid]
set_output_delay -clock clk  0.5  [get_ports {CNT1[7]}]
set_output_delay -clock clk  0.5  [get_ports {CNT1[6]}]
set_output_delay -clock clk  0.5  [get_ports {CNT1[5]}]
set_output_delay -clock clk  0.5  [get_ports {CNT1[4]}]
set_output_delay -clock clk  0.5  [get_ports {CNT1[3]}]
set_output_delay -clock clk  0.5  [get_ports {CNT1[2]}]
set_output_delay -clock clk  0.5  [get_ports {CNT1[1]}]
set_output_delay -clock clk  0.5  [get_ports {CNT1[0]}]
set_output_delay -clock clk  0.5  [get_ports {CNT2[7]}]
set_output_delay -clock clk  0.5  [get_ports {CNT2[6]}]
set_output_delay -clock clk  0.5  [get_ports {CNT2[5]}]
set_output_delay -clock clk  0.5  [get_ports {CNT2[4]}]
set_output_delay -clock clk  0.5  [get_ports {CNT2[3]}]
set_output_delay -clock clk  0.5  [get_ports {CNT2[2]}]
set_output_delay -clock clk  0.5  [get_ports {CNT2[1]}]
set_output_delay -clock clk  0.5  [get_ports {CNT2[0]}]
set_output_delay -clock clk  0.5  [get_ports {CNT3[7]}]
set_output_delay -clock clk  0.5  [get_ports {CNT3[6]}]
set_output_delay -clock clk  0.5  [get_ports {CNT3[5]}]
set_output_delay -clock clk  0.5  [get_ports {CNT3[4]}]
set_output_delay -clock clk  0.5  [get_ports {CNT3[3]}]
set_output_delay -clock clk  0.5  [get_ports {CNT3[2]}]
set_output_delay -clock clk  0.5  [get_ports {CNT3[1]}]
set_output_delay -clock clk  0.5  [get_ports {CNT3[0]}]
set_output_delay -clock clk  0.5  [get_ports {CNT4[7]}]
set_output_delay -clock clk  0.5  [get_ports {CNT4[6]}]
set_output_delay -clock clk  0.5  [get_ports {CNT4[5]}]
set_output_delay -clock clk  0.5  [get_ports {CNT4[4]}]
set_output_delay -clock clk  0.5  [get_ports {CNT4[3]}]
set_output_delay -clock clk  0.5  [get_ports {CNT4[2]}]
set_output_delay -clock clk  0.5  [get_ports {CNT4[1]}]
set_output_delay -clock clk  0.5  [get_ports {CNT4[0]}]
set_output_delay -clock clk  0.5  [get_ports {CNT5[7]}]
set_output_delay -clock clk  0.5  [get_ports {CNT5[6]}]
set_output_delay -clock clk  0.5  [get_ports {CNT5[5]}]
set_output_delay -clock clk  0.5  [get_ports {CNT5[4]}]
set_output_delay -clock clk  0.5  [get_ports {CNT5[3]}]
set_output_delay -clock clk  0.5  [get_ports {CNT5[2]}]
set_output_delay -clock clk  0.5  [get_ports {CNT5[1]}]
set_output_delay -clock clk  0.5  [get_ports {CNT5[0]}]
set_output_delay -clock clk  0.5  [get_ports {CNT6[7]}]
set_output_delay -clock clk  0.5  [get_ports {CNT6[6]}]
set_output_delay -clock clk  0.5  [get_ports {CNT6[5]}]
set_output_delay -clock clk  0.5  [get_ports {CNT6[4]}]
set_output_delay -clock clk  0.5  [get_ports {CNT6[3]}]
set_output_delay -clock clk  0.5  [get_ports {CNT6[2]}]
set_output_delay -clock clk  0.5  [get_ports {CNT6[1]}]
set_output_delay -clock clk  0.5  [get_ports {CNT6[0]}]
set_output_delay -clock clk  0.5  [get_ports code_valid]
set_output_delay -clock clk  0.5  [get_ports {HC1[7]}]
set_output_delay -clock clk  0.5  [get_ports {HC1[6]}]
set_output_delay -clock clk  0.5  [get_ports {HC1[5]}]
set_output_delay -clock clk  0.5  [get_ports {HC1[4]}]
set_output_delay -clock clk  0.5  [get_ports {HC1[3]}]
set_output_delay -clock clk  0.5  [get_ports {HC1[2]}]
set_output_delay -clock clk  0.5  [get_ports {HC1[1]}]
set_output_delay -clock clk  0.5  [get_ports {HC1[0]}]
set_output_delay -clock clk  0.5  [get_ports {HC2[7]}]
set_output_delay -clock clk  0.5  [get_ports {HC2[6]}]
set_output_delay -clock clk  0.5  [get_ports {HC2[5]}]
set_output_delay -clock clk  0.5  [get_ports {HC2[4]}]
set_output_delay -clock clk  0.5  [get_ports {HC2[3]}]
set_output_delay -clock clk  0.5  [get_ports {HC2[2]}]
set_output_delay -clock clk  0.5  [get_ports {HC2[1]}]
set_output_delay -clock clk  0.5  [get_ports {HC2[0]}]
set_output_delay -clock clk  0.5  [get_ports {HC3[7]}]
set_output_delay -clock clk  0.5  [get_ports {HC3[6]}]
set_output_delay -clock clk  0.5  [get_ports {HC3[5]}]
set_output_delay -clock clk  0.5  [get_ports {HC3[4]}]
set_output_delay -clock clk  0.5  [get_ports {HC3[3]}]
set_output_delay -clock clk  0.5  [get_ports {HC3[2]}]
set_output_delay -clock clk  0.5  [get_ports {HC3[1]}]
set_output_delay -clock clk  0.5  [get_ports {HC3[0]}]
set_output_delay -clock clk  0.5  [get_ports {HC4[7]}]
set_output_delay -clock clk  0.5  [get_ports {HC4[6]}]
set_output_delay -clock clk  0.5  [get_ports {HC4[5]}]
set_output_delay -clock clk  0.5  [get_ports {HC4[4]}]
set_output_delay -clock clk  0.5  [get_ports {HC4[3]}]
set_output_delay -clock clk  0.5  [get_ports {HC4[2]}]
set_output_delay -clock clk  0.5  [get_ports {HC4[1]}]
set_output_delay -clock clk  0.5  [get_ports {HC4[0]}]
set_output_delay -clock clk  0.5  [get_ports {HC5[7]}]
set_output_delay -clock clk  0.5  [get_ports {HC5[6]}]
set_output_delay -clock clk  0.5  [get_ports {HC5[5]}]
set_output_delay -clock clk  0.5  [get_ports {HC5[4]}]
set_output_delay -clock clk  0.5  [get_ports {HC5[3]}]
set_output_delay -clock clk  0.5  [get_ports {HC5[2]}]
set_output_delay -clock clk  0.5  [get_ports {HC5[1]}]
set_output_delay -clock clk  0.5  [get_ports {HC5[0]}]
set_output_delay -clock clk  0.5  [get_ports {HC6[7]}]
set_output_delay -clock clk  0.5  [get_ports {HC6[6]}]
set_output_delay -clock clk  0.5  [get_ports {HC6[5]}]
set_output_delay -clock clk  0.5  [get_ports {HC6[4]}]
set_output_delay -clock clk  0.5  [get_ports {HC6[3]}]
set_output_delay -clock clk  0.5  [get_ports {HC6[2]}]
set_output_delay -clock clk  0.5  [get_ports {HC6[1]}]
set_output_delay -clock clk  0.5  [get_ports {HC6[0]}]
set_output_delay -clock clk  0.5  [get_ports {M1[7]}]
set_output_delay -clock clk  0.5  [get_ports {M1[6]}]
set_output_delay -clock clk  0.5  [get_ports {M1[5]}]
set_output_delay -clock clk  0.5  [get_ports {M1[4]}]
set_output_delay -clock clk  0.5  [get_ports {M1[3]}]
set_output_delay -clock clk  0.5  [get_ports {M1[2]}]
set_output_delay -clock clk  0.5  [get_ports {M1[1]}]
set_output_delay -clock clk  0.5  [get_ports {M1[0]}]
set_output_delay -clock clk  0.5  [get_ports {M2[7]}]
set_output_delay -clock clk  0.5  [get_ports {M2[6]}]
set_output_delay -clock clk  0.5  [get_ports {M2[5]}]
set_output_delay -clock clk  0.5  [get_ports {M2[4]}]
set_output_delay -clock clk  0.5  [get_ports {M2[3]}]
set_output_delay -clock clk  0.5  [get_ports {M2[2]}]
set_output_delay -clock clk  0.5  [get_ports {M2[1]}]
set_output_delay -clock clk  0.5  [get_ports {M2[0]}]
set_output_delay -clock clk  0.5  [get_ports {M3[7]}]
set_output_delay -clock clk  0.5  [get_ports {M3[6]}]
set_output_delay -clock clk  0.5  [get_ports {M3[5]}]
set_output_delay -clock clk  0.5  [get_ports {M3[4]}]
set_output_delay -clock clk  0.5  [get_ports {M3[3]}]
set_output_delay -clock clk  0.5  [get_ports {M3[2]}]
set_output_delay -clock clk  0.5  [get_ports {M3[1]}]
set_output_delay -clock clk  0.5  [get_ports {M3[0]}]
set_output_delay -clock clk  0.5  [get_ports {M4[7]}]
set_output_delay -clock clk  0.5  [get_ports {M4[6]}]
set_output_delay -clock clk  0.5  [get_ports {M4[5]}]
set_output_delay -clock clk  0.5  [get_ports {M4[4]}]
set_output_delay -clock clk  0.5  [get_ports {M4[3]}]
set_output_delay -clock clk  0.5  [get_ports {M4[2]}]
set_output_delay -clock clk  0.5  [get_ports {M4[1]}]
set_output_delay -clock clk  0.5  [get_ports {M4[0]}]
set_output_delay -clock clk  0.5  [get_ports {M5[7]}]
set_output_delay -clock clk  0.5  [get_ports {M5[6]}]
set_output_delay -clock clk  0.5  [get_ports {M5[5]}]
set_output_delay -clock clk  0.5  [get_ports {M5[4]}]
set_output_delay -clock clk  0.5  [get_ports {M5[3]}]
set_output_delay -clock clk  0.5  [get_ports {M5[2]}]
set_output_delay -clock clk  0.5  [get_ports {M5[1]}]
set_output_delay -clock clk  0.5  [get_ports {M5[0]}]
set_output_delay -clock clk  0.5  [get_ports {M6[7]}]
set_output_delay -clock clk  0.5  [get_ports {M6[6]}]
set_output_delay -clock clk  0.5  [get_ports {M6[5]}]
set_output_delay -clock clk  0.5  [get_ports {M6[4]}]
set_output_delay -clock clk  0.5  [get_ports {M6[3]}]
set_output_delay -clock clk  0.5  [get_ports {M6[2]}]
set_output_delay -clock clk  0.5  [get_ports {M6[1]}]
set_output_delay -clock clk  0.5  [get_ports {M6[0]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports reset]
set_drive 1  [get_ports gray_valid]
set_drive 1  [get_ports {gray_data[7]}]
set_drive 1  [get_ports {gray_data[6]}]
set_drive 1  [get_ports {gray_data[5]}]
set_drive 1  [get_ports {gray_data[4]}]
set_drive 1  [get_ports {gray_data[3]}]
set_drive 1  [get_ports {gray_data[2]}]
set_drive 1  [get_ports {gray_data[1]}]
set_drive 1  [get_ports {gray_data[0]}]
