###################################################################

# Created by write_sdc on Fri Jan 31 07:41:29 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions slow -library slow
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 1 [get_ports {C1X[3]}]
set_load -pin_load 1 [get_ports {C1X[2]}]
set_load -pin_load 1 [get_ports {C1X[1]}]
set_load -pin_load 1 [get_ports {C1X[0]}]
set_load -pin_load 1 [get_ports {C1Y[3]}]
set_load -pin_load 1 [get_ports {C1Y[2]}]
set_load -pin_load 1 [get_ports {C1Y[1]}]
set_load -pin_load 1 [get_ports {C1Y[0]}]
set_load -pin_load 1 [get_ports {C2X[3]}]
set_load -pin_load 1 [get_ports {C2X[2]}]
set_load -pin_load 1 [get_ports {C2X[1]}]
set_load -pin_load 1 [get_ports {C2X[0]}]
set_load -pin_load 1 [get_ports {C2Y[3]}]
set_load -pin_load 1 [get_ports {C2Y[2]}]
set_load -pin_load 1 [get_ports {C2Y[1]}]
set_load -pin_load 1 [get_ports {C2Y[0]}]
set_load -pin_load 1 [get_ports DONE]
set_ideal_network [get_ports CLK]
create_clock [get_ports CLK]  -period 8  -waveform {0 4}
set_clock_latency 0.5  [get_clocks CLK]
set_clock_uncertainty 0.1  [get_clocks CLK]
set_input_delay -clock CLK  1  [get_ports RST]
set_input_delay -clock CLK  1  [get_ports {X[3]}]
set_input_delay -clock CLK  1  [get_ports {X[2]}]
set_input_delay -clock CLK  1  [get_ports {X[1]}]
set_input_delay -clock CLK  1  [get_ports {X[0]}]
set_input_delay -clock CLK  1  [get_ports {Y[3]}]
set_input_delay -clock CLK  1  [get_ports {Y[2]}]
set_input_delay -clock CLK  1  [get_ports {Y[1]}]
set_input_delay -clock CLK  1  [get_ports {Y[0]}]
set_output_delay -clock CLK  1  [get_ports {C1X[3]}]
set_output_delay -clock CLK  1  [get_ports {C1X[2]}]
set_output_delay -clock CLK  1  [get_ports {C1X[1]}]
set_output_delay -clock CLK  1  [get_ports {C1X[0]}]
set_output_delay -clock CLK  1  [get_ports {C1Y[3]}]
set_output_delay -clock CLK  1  [get_ports {C1Y[2]}]
set_output_delay -clock CLK  1  [get_ports {C1Y[1]}]
set_output_delay -clock CLK  1  [get_ports {C1Y[0]}]
set_output_delay -clock CLK  1  [get_ports {C2X[3]}]
set_output_delay -clock CLK  1  [get_ports {C2X[2]}]
set_output_delay -clock CLK  1  [get_ports {C2X[1]}]
set_output_delay -clock CLK  1  [get_ports {C2X[0]}]
set_output_delay -clock CLK  1  [get_ports {C2Y[3]}]
set_output_delay -clock CLK  1  [get_ports {C2Y[2]}]
set_output_delay -clock CLK  1  [get_ports {C2Y[1]}]
set_output_delay -clock CLK  1  [get_ports {C2Y[0]}]
set_output_delay -clock CLK  1  [get_ports DONE]
set_drive 0.1  [get_ports CLK]
set_drive 0.1  [get_ports RST]
set_drive 0.1  [get_ports {X[3]}]
set_drive 0.1  [get_ports {X[2]}]
set_drive 0.1  [get_ports {X[1]}]
set_drive 0.1  [get_ports {X[0]}]
set_drive 0.1  [get_ports {Y[3]}]
set_drive 0.1  [get_ports {Y[2]}]
set_drive 0.1  [get_ports {Y[1]}]
set_drive 0.1  [get_ports {Y[0]}]
