###################################################################

# Created by write_sdc on Sun Jan 26 14:43:24 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions slow -library slow
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 1 [get_ports busy]
set_load -pin_load 1 [get_ports valid]
set_load -pin_load 1 [get_ports {candidate[7]}]
set_load -pin_load 1 [get_ports {candidate[6]}]
set_load -pin_load 1 [get_ports {candidate[5]}]
set_load -pin_load 1 [get_ports {candidate[4]}]
set_load -pin_load 1 [get_ports {candidate[3]}]
set_load -pin_load 1 [get_ports {candidate[2]}]
set_load -pin_load 1 [get_ports {candidate[1]}]
set_load -pin_load 1 [get_ports {candidate[0]}]
set_max_fanout 20 [get_ports clk]
set_max_fanout 20 [get_ports rst]
set_max_fanout 20 [get_ports en]
set_max_fanout 20 [get_ports {central[23]}]
set_max_fanout 20 [get_ports {central[22]}]
set_max_fanout 20 [get_ports {central[21]}]
set_max_fanout 20 [get_ports {central[20]}]
set_max_fanout 20 [get_ports {central[19]}]
set_max_fanout 20 [get_ports {central[18]}]
set_max_fanout 20 [get_ports {central[17]}]
set_max_fanout 20 [get_ports {central[16]}]
set_max_fanout 20 [get_ports {central[15]}]
set_max_fanout 20 [get_ports {central[14]}]
set_max_fanout 20 [get_ports {central[13]}]
set_max_fanout 20 [get_ports {central[12]}]
set_max_fanout 20 [get_ports {central[11]}]
set_max_fanout 20 [get_ports {central[10]}]
set_max_fanout 20 [get_ports {central[9]}]
set_max_fanout 20 [get_ports {central[8]}]
set_max_fanout 20 [get_ports {central[7]}]
set_max_fanout 20 [get_ports {central[6]}]
set_max_fanout 20 [get_ports {central[5]}]
set_max_fanout 20 [get_ports {central[4]}]
set_max_fanout 20 [get_ports {central[3]}]
set_max_fanout 20 [get_ports {central[2]}]
set_max_fanout 20 [get_ports {central[1]}]
set_max_fanout 20 [get_ports {central[0]}]
set_max_fanout 20 [get_ports {radius[11]}]
set_max_fanout 20 [get_ports {radius[10]}]
set_max_fanout 20 [get_ports {radius[9]}]
set_max_fanout 20 [get_ports {radius[8]}]
set_max_fanout 20 [get_ports {radius[7]}]
set_max_fanout 20 [get_ports {radius[6]}]
set_max_fanout 20 [get_ports {radius[5]}]
set_max_fanout 20 [get_ports {radius[4]}]
set_max_fanout 20 [get_ports {radius[3]}]
set_max_fanout 20 [get_ports {radius[2]}]
set_max_fanout 20 [get_ports {radius[1]}]
set_max_fanout 20 [get_ports {radius[0]}]
set_max_fanout 20 [get_ports {mode[1]}]
set_max_fanout 20 [get_ports {mode[0]}]
create_clock [get_ports clk]  -period 8  -waveform {0 4}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty 0.1  [get_clocks clk]
set_input_delay -clock clk  4  [get_ports rst]
set_input_delay -clock clk  4  [get_ports en]
set_input_delay -clock clk  4  [get_ports {central[23]}]
set_input_delay -clock clk  4  [get_ports {central[22]}]
set_input_delay -clock clk  4  [get_ports {central[21]}]
set_input_delay -clock clk  4  [get_ports {central[20]}]
set_input_delay -clock clk  4  [get_ports {central[19]}]
set_input_delay -clock clk  4  [get_ports {central[18]}]
set_input_delay -clock clk  4  [get_ports {central[17]}]
set_input_delay -clock clk  4  [get_ports {central[16]}]
set_input_delay -clock clk  4  [get_ports {central[15]}]
set_input_delay -clock clk  4  [get_ports {central[14]}]
set_input_delay -clock clk  4  [get_ports {central[13]}]
set_input_delay -clock clk  4  [get_ports {central[12]}]
set_input_delay -clock clk  4  [get_ports {central[11]}]
set_input_delay -clock clk  4  [get_ports {central[10]}]
set_input_delay -clock clk  4  [get_ports {central[9]}]
set_input_delay -clock clk  4  [get_ports {central[8]}]
set_input_delay -clock clk  4  [get_ports {central[7]}]
set_input_delay -clock clk  4  [get_ports {central[6]}]
set_input_delay -clock clk  4  [get_ports {central[5]}]
set_input_delay -clock clk  4  [get_ports {central[4]}]
set_input_delay -clock clk  4  [get_ports {central[3]}]
set_input_delay -clock clk  4  [get_ports {central[2]}]
set_input_delay -clock clk  4  [get_ports {central[1]}]
set_input_delay -clock clk  4  [get_ports {central[0]}]
set_input_delay -clock clk  4  [get_ports {radius[11]}]
set_input_delay -clock clk  4  [get_ports {radius[10]}]
set_input_delay -clock clk  4  [get_ports {radius[9]}]
set_input_delay -clock clk  4  [get_ports {radius[8]}]
set_input_delay -clock clk  4  [get_ports {radius[7]}]
set_input_delay -clock clk  4  [get_ports {radius[6]}]
set_input_delay -clock clk  4  [get_ports {radius[5]}]
set_input_delay -clock clk  4  [get_ports {radius[4]}]
set_input_delay -clock clk  4  [get_ports {radius[3]}]
set_input_delay -clock clk  4  [get_ports {radius[2]}]
set_input_delay -clock clk  4  [get_ports {radius[1]}]
set_input_delay -clock clk  4  [get_ports {radius[0]}]
set_input_delay -clock clk  4  [get_ports {mode[1]}]
set_input_delay -clock clk  4  [get_ports {mode[0]}]
set_output_delay -clock clk  0.5  [get_ports busy]
set_output_delay -clock clk  0.5  [get_ports valid]
set_output_delay -clock clk  0.5  [get_ports {candidate[7]}]
set_output_delay -clock clk  0.5  [get_ports {candidate[6]}]
set_output_delay -clock clk  0.5  [get_ports {candidate[5]}]
set_output_delay -clock clk  0.5  [get_ports {candidate[4]}]
set_output_delay -clock clk  0.5  [get_ports {candidate[3]}]
set_output_delay -clock clk  0.5  [get_ports {candidate[2]}]
set_output_delay -clock clk  0.5  [get_ports {candidate[1]}]
set_output_delay -clock clk  0.5  [get_ports {candidate[0]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports rst]
set_drive 1  [get_ports en]
set_drive 1  [get_ports {central[23]}]
set_drive 1  [get_ports {central[22]}]
set_drive 1  [get_ports {central[21]}]
set_drive 1  [get_ports {central[20]}]
set_drive 1  [get_ports {central[19]}]
set_drive 1  [get_ports {central[18]}]
set_drive 1  [get_ports {central[17]}]
set_drive 1  [get_ports {central[16]}]
set_drive 1  [get_ports {central[15]}]
set_drive 1  [get_ports {central[14]}]
set_drive 1  [get_ports {central[13]}]
set_drive 1  [get_ports {central[12]}]
set_drive 1  [get_ports {central[11]}]
set_drive 1  [get_ports {central[10]}]
set_drive 1  [get_ports {central[9]}]
set_drive 1  [get_ports {central[8]}]
set_drive 1  [get_ports {central[7]}]
set_drive 1  [get_ports {central[6]}]
set_drive 1  [get_ports {central[5]}]
set_drive 1  [get_ports {central[4]}]
set_drive 1  [get_ports {central[3]}]
set_drive 1  [get_ports {central[2]}]
set_drive 1  [get_ports {central[1]}]
set_drive 1  [get_ports {central[0]}]
set_drive 1  [get_ports {radius[11]}]
set_drive 1  [get_ports {radius[10]}]
set_drive 1  [get_ports {radius[9]}]
set_drive 1  [get_ports {radius[8]}]
set_drive 1  [get_ports {radius[7]}]
set_drive 1  [get_ports {radius[6]}]
set_drive 1  [get_ports {radius[5]}]
set_drive 1  [get_ports {radius[4]}]
set_drive 1  [get_ports {radius[3]}]
set_drive 1  [get_ports {radius[2]}]
set_drive 1  [get_ports {radius[1]}]
set_drive 1  [get_ports {radius[0]}]
set_drive 1  [get_ports {mode[1]}]
set_drive 1  [get_ports {mode[0]}]
