###################################################################

# Created by write_sdc on Fri Jan 31 01:27:32 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions slow -library slow
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 1 [get_ports {W[2]}]
set_load -pin_load 1 [get_ports {W[1]}]
set_load -pin_load 1 [get_ports {W[0]}]
set_load -pin_load 1 [get_ports {J[2]}]
set_load -pin_load 1 [get_ports {J[1]}]
set_load -pin_load 1 [get_ports {J[0]}]
set_load -pin_load 1 [get_ports {MatchCount[3]}]
set_load -pin_load 1 [get_ports {MatchCount[2]}]
set_load -pin_load 1 [get_ports {MatchCount[1]}]
set_load -pin_load 1 [get_ports {MatchCount[0]}]
set_load -pin_load 1 [get_ports {MinCost[9]}]
set_load -pin_load 1 [get_ports {MinCost[8]}]
set_load -pin_load 1 [get_ports {MinCost[7]}]
set_load -pin_load 1 [get_ports {MinCost[6]}]
set_load -pin_load 1 [get_ports {MinCost[5]}]
set_load -pin_load 1 [get_ports {MinCost[4]}]
set_load -pin_load 1 [get_ports {MinCost[3]}]
set_load -pin_load 1 [get_ports {MinCost[2]}]
set_load -pin_load 1 [get_ports {MinCost[1]}]
set_load -pin_load 1 [get_ports {MinCost[0]}]
set_load -pin_load 1 [get_ports Valid]
set_max_fanout 20 [get_ports CLK]
set_max_fanout 20 [get_ports RST]
set_max_fanout 20 [get_ports {Cost[6]}]
set_max_fanout 20 [get_ports {Cost[5]}]
set_max_fanout 20 [get_ports {Cost[4]}]
set_max_fanout 20 [get_ports {Cost[3]}]
set_max_fanout 20 [get_ports {Cost[2]}]
set_max_fanout 20 [get_ports {Cost[1]}]
set_max_fanout 20 [get_ports {Cost[0]}]
create_clock [get_ports CLK]  -period 10  -waveform {0 5}
set_clock_latency 0.5  [get_clocks CLK]
set_clock_uncertainty 0.1  [get_clocks CLK]
set_input_delay -clock CLK  -clock_fall  0  [get_ports RST]
set_input_delay -clock CLK  -clock_fall  0  [get_ports {Cost[6]}]
set_input_delay -clock CLK  -clock_fall  0  [get_ports {Cost[5]}]
set_input_delay -clock CLK  -clock_fall  0  [get_ports {Cost[4]}]
set_input_delay -clock CLK  -clock_fall  0  [get_ports {Cost[3]}]
set_input_delay -clock CLK  -clock_fall  0  [get_ports {Cost[2]}]
set_input_delay -clock CLK  -clock_fall  0  [get_ports {Cost[1]}]
set_input_delay -clock CLK  -clock_fall  0  [get_ports {Cost[0]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {W[2]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {W[1]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {W[0]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {J[2]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {J[1]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {J[0]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MatchCount[3]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MatchCount[2]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MatchCount[1]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MatchCount[0]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MinCost[9]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MinCost[8]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MinCost[7]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MinCost[6]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MinCost[5]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MinCost[4]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MinCost[3]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MinCost[2]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MinCost[1]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports {MinCost[0]}]
set_output_delay -clock CLK  -clock_fall  0  [get_ports Valid]
set_drive 0.1  [get_ports CLK]
set_drive 0.1  [get_ports RST]
set_drive 0.1  [get_ports {Cost[6]}]
set_drive 0.1  [get_ports {Cost[5]}]
set_drive 0.1  [get_ports {Cost[4]}]
set_drive 0.1  [get_ports {Cost[3]}]
set_drive 0.1  [get_ports {Cost[2]}]
set_drive 0.1  [get_ports {Cost[1]}]
set_drive 0.1  [get_ports {Cost[0]}]
